-- CreateTable
CREATE TABLE "yacht" (
    "id" SERIAL NOT NULL,
    "builder" TEXT,
    "model" TEXT NOT NULL,
    "engines" TEXT,
    "length" DOUBLE PRECISION NOT NULL,
    "beam" DOUBLE PRECISION,
    "beam_open_platform" DOUBLE PRECISION,
    "draft" DOUBLE PRECISION,
    "cruise_speed" DOUBLE PRECISION,
    "max_speed" DOUBLE PRECISION,
    "cabins" INTEGER NOT NULL,
    "max_guests" INTEGER,
    "max_sleeping" INTEGER,
    "consumption" TEXT,
    "autonomy" TEXT,
    "fuel_capacity" INTEGER,
    "water_capacity" INTEGER,
    "navigation_class" TEXT,
    "dry_weight" DOUBLE PRECISION,
    "hull" TEXT,
    "status" TEXT,
    "available" BOOLEAN NOT NULL,
    "rating" DOUBLE PRECISION,
    "reviews_count" INTEGER,
    "city" TEXT NOT NULL,
    "provider_id" INTEGER,
    "price_day" DOUBLE PRECISION,
    "year" INTEGER,
    "region" TEXT,
    "currency" TEXT NOT NULL,
    "length_unit" TEXT NOT NULL,
    "map_iframe_src" TEXT,
    "price_hour" DOUBLE PRECISION,
    "price_week" DOUBLE PRECISION,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "yacht_pkey" PRIMARY KEY ("id")
);
