-- CreateTable
CREATE TABLE "property" (
    "id" SERIAL NOT NULL,
    "title" TEXT,
    "description" TEXT,
    "city" TEXT,
    "zip_code" TEXT,
    "type" TEXT,
    "surface" DOUBLE PRECISION,
    "rooms" INTEGER,
    "bedrooms" INTEGER,
    "bathrooms" INTEGER,
    "price" DOUBLE PRECISION,
    "reference" TEXT,
    "year" INTEGER,
    "for_sale" BOOLEAN,
    "is_off_market" BOOLEAN,
    "region" TEXT,
    "available" BOOLEAN,
    "status" TEXT,
    "rating" DOUBLE PRECISION,
    "reviews_count" INTEGER,
    "surface_unit" TEXT,
    "currency" TEXT,
    "map_iframe_src" TEXT,
    "provider_id" INTEGER,
    "price_day" DOUBLE PRECISION,
    "max_guests" INTEGER,
    "beds" INTEGER,
    "terrace_surface" DOUBLE PRECISION,
    "has_terrace" BOOLEAN,
    "has_balcony" BOOLEAN,
    "pets_allowed" BOOLEAN,
    "parties_allowed" BOOLEAN,
    "check_in_from" TEXT,
    "check_out_before" TEXT,
    "amenities" JSONB,
    "bed_distribution" JSONB,
    "price_week" DOUBLE PRECISION,
    "price_month" DOUBLE PRECISION,

    CONSTRAINT "property_pkey" PRIMARY KEY ("id")
);
