// One-off seed for the 10 launch articles of the Syrama Yachting blog.
// Writes to `yachting_blog_post` (NOT `blog_post` — see schema.prisma).
// Idempotent: upserts by slug, so re-running edits in place rather than
// duplicating. Run once with:  node prisma/seed-blog.mjs
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

function readingMinutes(content) {
  const words = content.reduce((n, b) => {
    if (b.type === 'list') return n + b.items.join(' ').split(/\s+/).length
    if (b.text) return n + b.text.split(/\s+/).length
    return n
  }, 0)
  return Math.max(1, Math.round(words / 200))
}

const P = (text) => ({ type: 'paragraph', text })
const H = (text) => ({ type: 'heading', text })
const L = (items) => ({ type: 'list', items })
const Q = (text, attribution) => ({ type: 'quote', text, ...(attribution ? { attribution } : {}) })

const posts = [
  // 1 ---------------------------------------------------------------
  {
    slug: 'french-riviera-yacht-charter-guide',
    title: 'The Ultimate Guide to Chartering a Yacht on the French Riviera',
    metaTitle: 'French Riviera Yacht Charter: The Complete Guide',
    metaDescription: 'How to charter a yacht on the French Riviera: where to cruise, when to go, what a week costs, and how to plan an itinerary from Cannes to Monaco.',
    excerpt: 'The stretch of coast between Saint-Tropez and Menton is the most chartered water in the Mediterranean. Here is how to plan a week on it properly.',
    category: 'Charter Guides',
    tags: ['French Riviera', 'Charter Guides', 'Cannes', 'Monaco', 'Saint-Tropez'],
    coverImage: '/images/regions/French_Riviera.webp',
    coverImageAlt: 'Motor yachts berthed in the old port of Saint-Tropez on the French Riviera',
    publishedAt: new Date('2026-06-18T09:00:00Z'),
    content: [
      P("The French Riviera has a head start on every other charter destination in the Mediterranean, and it is not really about the scenery. It is that everything a charter needs is packed into 70 nautical miles of coast: deep-water berths in every town, a fuel dock you are never more than an hour from, provisioning that can deliver caviar or a spare fender to the passerelle within the day, and more crew, brokers and refit yards than anywhere else on the sea. You can be ambitious with an itinerary here because the infrastructure quietly removes the friction."),
      P("That convenience is also why the coast can feel crowded in August, and why a good week depends less on the yacht than on the plan. This guide is about the plan."),
      H("When to go"),
      P("The season runs from May to late September. Each month has a different character, and they are genuinely different, not marketing gloss."),
      P("May and June are the quiet reward months. The water is warming, the light is long, the anchorages off the Îles de Lérins and Cap-Ferrat are half empty, and the towns still belong to the people who live in them. The one caveat is the [Cannes](/yacht-charter/french-riviera/cannes) events calendar — the Film Festival in mid-May and a run of trade shows push berths and prices up sharply for those specific weeks."),
      P("July and August are peak in every sense: warmest water, longest days, every restaurant ashore fully booked, and the popular bays busy from mid-morning. If you are coming with children and the swimming matters more than the solitude, this is still the right window — you just anchor earlier and eat aboard more often."),
      P("September is the connoisseur's month. The sea holds its summer temperature into early October, the crowds thin out after the first week, and prices soften. If your dates are flexible, this is the week to ask for. We go through the trade-offs month by month in [a separate guide to timing a Mediterranean charter](/blog/best-time-charter-yacht-mediterranean)."),
      H("The coastline, west to east"),
      P("It helps to have a mental map before you plan, because the Riviera is not uniform. Roughly from west to east:"),
      L([
        "The Gulf of Saint-Tropez and the Var coast — the widest anchorages, the Pampelonne beach clubs, and the most 'scene' in summer. Pretty inland villages behind it if you want a day off the water.",
        "Cannes and the Îles de Lérins — the festival town, and two small wooded islands ten minutes offshore that are the best easy anchorage on the coast once the day boats leave at six.",
        "Antibes and Cap d'Antibes — Port Vauban, the largest marina in Europe, and a headland of quiet anchorages and grand villas. A practical base with an old town worth an evening.",
        "The Baie de Villefranche and Cap-Ferrat — one of the deepest natural harbours in the Mediterranean, reliably calm, and a short tender from some of the best coastal walking on the Riviera.",
        "Monaco and Menton — the Principality, and then the last stretch of French coast before Italy, quieter and often overlooked.",
      ]),
      H("How a week usually runs"),
      P("Most Riviera charters are based out of one of three hubs — [Cannes](/yacht-charter/french-riviera/cannes), Antibes or [Monaco](/yacht-charter/french-riviera/monaco) — and work east or west from there. A classic seven-night loop looks something like this:"),
      L([
        "Embark in Cannes, anchor for the first night off the Îles de Lérins, a ten-minute tender ride from the Croisette but a different world once the day boats leave.",
        "West to the Gulf of [Saint-Tropez](/yacht-charter/french-riviera/saint-tropez): two nights, one on the hook off Pampelonne for lunch and swimming, one stern-to in the old port if you want an evening ashore.",
        "Back east past [Antibes](/yacht-charter/french-riviera/antibes) and Cap-Ferrat, with a long lunch stop in the Baie de Villefranche.",
        "A night in [Monaco](/yacht-charter/french-riviera/monaco), ideally timed to something: a concert, a match, or just dinner and the walk up to the Casino square.",
        "The last full day pointed at Menton and the Italian border, or back west for a final anchorage swim before disembarkation.",
      ]),
      P("None of that is fixed. The point of a private charter is that the captain rewrites the plan over breakfast based on the wind and what you feel like — see [what a crewed charter actually involves](/blog/what-to-expect-crewed-yacht-charter) for how that works day to day."),
      H("Weather to plan around"),
      P("The Riviera is a settled place to sail, but two winds shape a week. The mistral is a strong, cold northwesterly that funnels down the Rhône valley and out over the western Riviera — it can blow hard for two or three days and makes the Gulf of Saint-Tropez uncomfortable, though the eastern anchorages near Cap-Ferrat stay sheltered. The easterly, less common in summer, does the reverse. A captain who knows the coast simply flips the itinerary to sit on the lee side of whatever is blowing, which is why the loop above works in either direction."),
      H("What it costs"),
      P("Charter pricing on the Riviera follows the same logic as everywhere in the Mediterranean: a base fee for the week set by the yacht's size and age, plus an Advance Provisioning Allowance — usually around 30 percent of the base — that covers fuel, food, berthing, and anything else consumed during the trip. Whatever is not spent from the APA is returned at the end."),
      P("As a rough sense of scale, a well-kept motor yacht in the 25-to-30-metre range with a crew of four or five sits in the low tens of thousands of euros per week in base fee during peak season, before APA and the customary crew gratuity. Smaller day-and-weekend boats are a fraction of that. We cover this properly in [a separate guide to charter costs](/blog/how-much-does-yacht-charter-cost)."),
      P("The number that surprises people is not the base fee — it is how much the APA can swing depending on how the week is run. A week spent mostly at anchor, eating aboard, moving short distances, comes in well under budget. A week of long passages and a berth in a marquee port every night can use all of it. A berth in Monaco or the old port of Saint-Tropez in August is a four-figure night; the anchorage two hundred metres away is free and often nicer."),
      H("A few things first-timers get wrong"),
      L([
        "Trying to see the whole coast. Seven nights is four or five real stops. The Riviera rewards staying put — a morning swim, a long lunch, a walk, dinner — more than it rewards covering ground.",
        "Booking marina nights 'to be safe'. Your captain will get you a berth when you actually want one. Most nights, the anchorage is the better choice anyway.",
        "Underestimating the tender. A lot of a Riviera week is tender rides ashore for dinner or to a beach club. A yacht with a fast, comfortable tender and a deckhand who enjoys running it changes the trip.",
      ]),
      H("Where the Riviera fits against everywhere else"),
      P("If this is a first Mediterranean charter, the Riviera is the safe, high-reward choice: short distances, no language barrier for the crew, everything reachable, and enough variety in a week that no two days feel the same. It rewards people who want their evenings ashore."),
      P("If you have done it before and want more sea and fewer marinas, the natural next steps are [Corsica and Sardinia](/yacht-charter/corsica) across the Ligurian Sea, or [the Greek islands](/yacht-charter/greece) further east. But most people who charter the Riviera once come back to it, because the thing it does — a serious yacht, a serious coastline, and none of the logistics landing on you — is genuinely hard to find elsewhere."),
      P("When you are ready to look at specific yachts and dates, our [French Riviera charter fleet](/yacht-charter/french-riviera) is the place to start, or [speak to an advisor](/yacht-charter) about shaping a week around what you actually want from it."),
    ],
  },
  // 2 ---------------------------------------------------------------
  {
    slug: 'greece-yacht-charter-cyclades-ionian',
    title: 'Yacht Charter in Greece: The Cyclades, the Ionian and Beyond',
    metaTitle: 'Greece Yacht Charter: Cyclades vs Ionian Guide',
    metaDescription: 'A practical guide to chartering a yacht in Greece — how the Cyclades and Ionian differ, when to sail each, and how to plan an island-hopping route.',
    excerpt: 'Greece is not one charter destination. The wind, the distances and the feel change completely depending on which sea you point the bow at.',
    category: 'Destinations',
    tags: ['Greece', 'Destinations', 'Cyclades', 'Ionian', 'Charter Guides'],
    coverImage: '/images/regions/Greece.webp',
    coverImageAlt: 'A motor yacht moored on the Greek coast, framed by pine trees',
    publishedAt: new Date('2026-06-29T09:00:00Z'),
    content: [
      P("People say they want to charter \"in Greece\" the way they say they want to charter \"in the Caribbean\" — as if it were a single place with a single character. It is not. The two main cruising grounds, the Cyclades and the Ionian, are on opposite sides of the mainland and feel almost nothing alike. Choosing between them is the first and most important decision, and it comes down to what you want the sailing itself to feel like."),
      H("The Cyclades: wind, light and distance"),
      P("The Cyclades are the islands most people picture — Mykonos, Paros, Naxos, Santorini, and the smaller, quieter ones around them. Whitewashed, treeless, dramatic, and set in an open sea that gets a proper northerly wind called the meltemi through July and August."),
      P("That wind is the defining fact of a Cyclades charter. On a good day it fills the sails and the passages between islands are exhilarating. On a strong meltemi day it can pin you in a harbour for 24 hours, and any itinerary here has to be built with slack in it. A captain who knows the archipelago will always have a plan B anchorage on the lee side of wherever you are heading."),
      P("Distances are longer than people expect — three to five hours between many of the islands — so a week in the Cyclades is more about passage-making and fewer, longer stops than it is about drifting between coves. It suits people who genuinely enjoy being under way."),
      P("The lesser-known islands are the reward for the effort. Amorgos, Folegandros, Sifnos and Serifos have the Cycladic drama without the crowds, better tavernas than the famous islands, and anchorages where you might be the only yacht. A good week here spends one night in Mykonos or the caldera at Santorini for the spectacle, and the rest somewhere quieter."),
      H("The Ionian: calm water and short hops"),
      P("The Ionian, on the west side, is the opposite. Green islands — Corfu, Paxos, Lefkada, Kefalonia, Ithaca — close together, in sheltered water, with a gentle afternoon breeze rather than a gale. Anchorages are often a 45-minute motor or sail apart, which means you can be swimming somewhere new by mid-morning and still have the afternoon there."),
      P("This is the Greece for a relaxed week, for families, and for anyone whose crew includes people who are not sure they like boats yet. The famous stops — the blue water of the Paxos sea caves, the beach at Antipaxos, the tavernas on the Lefkada canal, the horseshoe bay at Ithaca — are all reachable without a hard day's sailing between them."),
      P("The Ionian also has the more consistent underwater visibility of the two, and some of the best snorkelling in Greece around Paxos and the Lefkada coast. If diving or snorkelling matters to your group, this is the side to be on."),
      Q("The Ionian forgives a loose plan. The Cyclades punish one.", "A Greek charter captain we work with"),
      H("The Saronic and the Sporades"),
      P("Two smaller cruising grounds are worth knowing about. The Saronic islands — Hydra, Poros, Spetses — sit just south of Athens and make an excellent gentle three or four days, often used as the first half of a Cyclades charter to ease into it. Hydra, with no cars and a perfect stone harbour, is a highlight of Greek cruising in its own right. The Sporades, off the eastern mainland, are green, quiet and centred on the marine park around Alonnisos — the least-chartered of the Greek grounds and the one to consider if solitude is the priority."),
      H("When to go"),
      P("May, June and September are the sweet spots for both regions: warm enough to swim, before or after the meltemi peaks, and with the anchorages far less contested than in high summer. July and August bring the best swimming temperatures but also the strongest winds in the Cyclades and the biggest crowds everywhere — Mykonos and Santorini in August are a scene, and whether that is the point of the trip or the thing to avoid is a personal question."),
      H("Sail or motor"),
      P("Greece is one of the few Mediterranean destinations where a sailing yacht is often the better choice, not just the romantic one. The Ionian breeze and the Cyclades meltemi both give you real, usable wind, and a sailing yacht at anchor in a quiet bay with the engines off is a particular kind of quiet. Motor yachts still make sense for larger groups or for covering the longer Cyclades distances quickly, but do not default to one out of habit here."),
      H("Eating, and the tavernas"),
      P("Greek charter food splits in two, and the best weeks use both. Aboard, a good chef leans into what the islands do well — grilled fish landed that morning, tomatoes that taste of something, olive oil poured with abandon, a lunch of small plates on the aft deck that runs for two hours. Ashore, the reward is the taverna, and the rule is to walk past the ones on the harbour front with laminated menus and photos, and find the one up a back street with six tables and a handwritten board. On the smaller islands the crew will know it, or the harbour will tell you — whichever place the local fishermen eat at is the answer. Book nothing; just turn up around nine when Greece actually has dinner."),
      H("Planning the route"),
      P("A first Greek charter usually starts from Athens (for the Cyclades, often via the Saronic islands as a gentler warm-up) or from Corfu or Lefkada (for the Ionian). Whichever you choose, resist the urge to see everything. A week is five or six real stops, not ten. The islands reward staying put for a full day — a morning swim, a long lunch, a walk to a village, dinner back aboard or ashore — far more than they reward ticking them off."),
      P("If you have chartered the [French Riviera](/yacht-charter/french-riviera) or the [Balearics](/yacht-charter/balearic-islands) and want more sea and fewer marinas, Greece is the obvious next move. Our [Greece charter fleet](/yacht-charter/greece) covers both cruising grounds, and an advisor can tell you honestly which one fits the week you are picturing — [start there](/yacht-charter)."),
    ],
  },
  // 3 ---------------------------------------------------------------
  {
    slug: 'dubai-yacht-charter-arabian-gulf',
    title: 'Dubai Yacht Charter: Cruising the Arabian Gulf in Style',
    metaTitle: 'Dubai Yacht Charter Guide: Marina, Palm & The Gulf',
    metaDescription: 'What a Dubai yacht charter is really like — the marina scene, the World Islands, when to go, and how a day or week on the Arabian Gulf comes together.',
    excerpt: 'Dubai charters are their own thing: shorter, more urban, built around a skyline rather than a coastline of villages. That is a feature, not a compromise.',
    category: 'Dubai Yacht Charter',
    tags: ['Dubai', 'Emirates', 'Arabian Gulf', 'Charter Guides'],
    coverImage: '/images/regions/Dubai.webp',
    coverImageAlt: 'Yachts berthed in Dubai Marina beneath the skyline',
    publishedAt: new Date('2026-07-08T09:00:00Z'),
    content: [
      P("A Dubai charter does not look like a Mediterranean one, and people who arrive expecting island-hopping are briefly disoriented. There are no fishing villages to walk into, no vineyard-backed bays. What there is instead: one of the most photographed skylines on earth seen from the water, warm flat sea almost year-round, and a marina culture built entirely around exactly this."),
      P("Once you stop comparing it to the Med and take it on its own terms, it is one of the easiest and most reliably good charters anywhere — a [luxury yacht charter in Dubai](/yacht-charter/emirates/dubai) is closer to a very good afternoon on the water with an extraordinary backdrop than to a week of seamanship."),
      H("Where you actually go"),
      P("Most Dubai charters run out of Dubai Marina or Dubai Harbour, and the cruising ground is a compact set of landmarks rather than a coastline — the Marina and JBR waterfront, Palm Jumeirah and the Atlantis, the Burj Al Arab, and the quieter anchorages out at the World Islands. Which of those a charter actually covers depends on how long you book and where you leave from; [our guide to the best yacht routes in Dubai](/blog/dubai-yacht-charter-routes) breaks it down by duration."),
      P("As a rough sense: a half-day covers the Marina and the Palm comfortably, a full day adds the World Islands and real swimming time, and overnight charters anchor out where it is dark enough to see stars."),
      H("Half a day, a full day, or longer"),
      P("Getting the duration right matters more here than in the Med, where a week is the default. A three-hour sunset charter is the classic first booking and genuinely delivers — the light on the towers, a swim off the back, drinks on the flybridge. A full day gives you the swimming time and the World Islands, and stops feeling rushed. Two or three nights turns it into a proper trip: mornings on anchor before the traffic builds, the city at night from the water, and enough time that the pace slows down. Beyond that, the interesting move is heading away from the skyline entirely toward the quieter Gulf."),
      H("When to go"),
      P("The season is the inverse of the Mediterranean. October to April is the window: warm days in the mid-20s to low-30s Celsius, comfortable evenings, calm sea. This is also peak visitor season in the city, so book berths and dates ahead."),
      P("May to September is intense heat — 40 degrees and high humidity — and while the boats still run, and the sea is bath-warm, most people find the middle of the day is spent under the bimini or inside in the air conditioning. If you are coming in summer, an early-morning or sunset charter is far more pleasant than a midday one."),
      H("The style of the thing"),
      P("Dubai charters lean glamorous and social. The typical booking is a group — family, friends, a celebration — on a large flybridge motor yacht, with catering, music, and the tender running people to a sandbank for photos. It is less about seamanship and more about a very good afternoon on the water with a backdrop that does a lot of the work."),
      P("That said, the quieter version exists. An early departure, a slow loop of the Palm before the traffic builds, an anchorage off the World Islands with breakfast on the foredeck — Dubai does calm mornings beautifully, and almost nobody asks for them."),
      H("Practicalities"),
      P("Chartering here is straightforward. The fleet is modern, the crews are used to international guests, and provisioning and concierge are quick and comprehensive. Alcohol is served aboard licensed charter yachts. Swimwear is fine on board and at private beach clubs; normal modesty applies at public landing points. A good operator briefs you on all of this before you step aboard so none of it is a surprise. Bring reef-safe sun protection, more than you think — the sun is stronger than the pleasant air temperature suggests."),
      H("Booking a charter that lives up to the photos"),
      P("The Dubai charter market is large and uneven. The visible end of it is a lot of similar-looking flybridge boats marketed on price for two-hour party trips, and some of them are tired below the gloss of the brochure. The gap between a well-kept, well-crewed yacht and a merely adequate one is wide here, and it is not always obvious from a listing. A few things to check before booking: how recent the last refit was, whether the crew is permanent or rotated in per charter, what the catering actually consists of rather than the word 'catering', and whether the air conditioning runs at anchor without the generators becoming the loudest thing aboard. An advisor who knows the fleet can steer you past the ones that photograph better than they charter."),
      H("How it fits with the rest of a trip"),
      P("Very few people fly to Dubai only to charter. It is almost always an add-on — a day carved out of a business trip, a stopover on the way to the Maldives or the Seychelles, a family week in the city. That is the right way to think about it: one of the highest-return half-days you can slot into a wider itinerary. If your yachting year is otherwise a Mediterranean summer, a winter day on the Gulf is a good way to keep it going. Pair it with a few days in the city and it becomes a proper short break rather than an errand."),
      P("Our [Dubai charter fleet](/yacht-charter/emirates/dubai) runs year-round, and an advisor can match the boat to the group and the occasion — [get in touch](/yacht-charter)."),
    ],
  },
  // 4 ---------------------------------------------------------------
  {
    slug: 'caribbean-yacht-charter-when-where',
    title: 'Caribbean Yacht Charter: When and Where to Sail',
    metaTitle: 'Caribbean Yacht Charter: When to Go & Where',
    metaDescription: 'A guide to chartering a yacht in the Caribbean — the difference between the BVI, St Barths and the Grenadines, the season, and hurricane-window timing.',
    excerpt: 'The Caribbean is a winter charter destination with a hard weather calendar. Get the timing right and it is the best sailing water in the Atlantic.',
    category: 'Destinations',
    tags: ['Caribbean', 'Destinations', 'BVI', 'St Barths', 'Charter Guides'],
    coverImage: '/images/regions/Caribbean.webp',
    coverImageAlt: 'A superyacht moored in a sheltered Caribbean harbour',
    publishedAt: new Date('2026-07-19T09:00:00Z'),
    content: [
      P("The Caribbean charter season exists because of two facts. The first is that from roughly December to April, the trade winds blow steadily from the east at a comfortable 15 to 20 knots, the sky is mostly clear, and the water sits around 27 degrees. The second is that from June to November it is hurricane season, and the serious charter fleet leaves. Everything about planning a Caribbean charter follows from those two facts."),
      H("The season, precisely"),
      P("Mid-December to mid-April is prime. Christmas and New Year is the busiest and most expensive fortnight of the year anywhere in the charter world, and Caribbean berths and boats for that window are often reserved a year ahead. January to March is the quieter, better-value heart of the season with the most reliable weather."),
      P("May and late November are shoulder — cheaper, still generally fine, but you are closer to the edge of the weather window and should be comfortable with a flexible plan. June through November, most guests are chartering in the Mediterranean instead, and the yachts follow them across the Atlantic."),
      H("The three main cruising grounds"),
      P("\"The Caribbean\" covers a lot of sea. For charter purposes it splits into a few distinct areas, and they are genuinely different trips."),
      H("The British Virgin Islands"),
      P("The BVI is the beginners' Caribbean, and that is a compliment. The islands sit in a tight cluster around the Sir Francis Drake Channel, so you are rarely more than a couple of hours' sail apart, always in sight of land, and always in protected water. The anchorages — the Baths on Virgin Gorda, the Bight on Norman Island, Cane Garden Bay on Tortola, the sandbar at Anegada — are famous for good reason. This is the easiest place in the region to have a relaxed week, and where most catamaran charters go. The beach bars are an institution: the Soggy Dollar at White Bay, the Willy T floating bar, Foxy's on Jost Van Dyke."),
      H("St Barths and the northern islands"),
      P("[St Barths](/yacht-charter/caribbean) is the Caribbean's answer to Saint-Tropez: a small, chic French island with a harbour full of superyachts, particularly over New Year. Pair it with St Martin, Anguilla and its extraordinary beaches, and the quieter St Kitts and Nevis, and you have a week with more contrast — a night in Gustavia, a day anchored off a deserted cay. The distances are a little longer than the BVI and the sailing more open, which suits people who want the passages to feel like sailing."),
      H("The Grenadines"),
      P("The southern Grenadines — Bequia, Mustique, the Tobago Cays — are the wildest and least developed of the three. More sailing, fewer marinas, the best snorkelling in the region by some distance, and a real sense of being somewhere remote. The Tobago Cays, a cluster of uninhabited islands protected by a horseshoe reef, with turtles in the shallows, is one of the great anchorages anywhere. This is the Caribbean for people who have done the BVI and want more."),
      H("Catamaran or monohull"),
      P("The Caribbean is catamaran country. The steady beam-reaching trade winds suit them, the flat sailing is comfortable for guests who are not sailors, the shallow draft opens up anchorages a monohull cannot enter, and the deck space matters when you are living outside for a week. Monohull sailing yachts and motor yachts both charter here too — a large motor yacht makes sense for a group that wants range, air conditioning throughout and less dependence on wind — but if you have a choice and no strong preference, the cat is usually the right call. We touch on this trade-off in [our buyer's guide](/blog/buyers-guide-choosing-the-right-yacht) too, since it applies to ownership as much as charter."),
      H("What a week actually looks like"),
      P("Trade-wind sailing has a rhythm. You wake at anchor, swim before breakfast, sail two or three hours in the morning when the wind is steady, arrive somewhere new for lunch, spend the afternoon in the water or ashore, and settle for the night before the light goes. It is not a restful-in-a-spa-sense holiday — you are outside, salty and a little sun-tired every evening — but it is the good kind of tired, and the sailing itself is a large part of the point in a way it is not everywhere."),
      H("Getting there"),
      P("Access is via Antigua, St Martin, or Tortola for the BVI, usually with a connection through a US or European hub. Build in a buffer day at each end — Caribbean connections are not always same-day, and you do not want to lose a charter day to a missed flight. A night in a hotel before boarding is a good idea regardless: you start the charter rested rather than jet-lagged."),
      P("If your yachting is normally a Mediterranean summer, a Caribbean week fills the other half of the year with the best trade-wind sailing in the Atlantic. Our [Caribbean charter fleet](/yacht-charter/caribbean) covers all three cruising grounds — [talk to an advisor](/yacht-charter) about which one and which window fits."),
    ],
  },
  // 5 ---------------------------------------------------------------
  {
    slug: 'how-much-does-yacht-charter-cost',
    title: 'How Much Does It Cost to Charter a Yacht? A Practical Guide',
    metaTitle: 'How Much Does a Yacht Charter Cost? Full Breakdown',
    metaDescription: 'A clear breakdown of what a luxury yacht charter costs — the base fee, APA, VAT, crew gratuity — and what actually moves the total up or down.',
    excerpt: 'The base fee is the number people quote. It is rarely the number that decides whether a charter felt expensive.',
    category: 'Charter Guides',
    tags: ['Charter Guides', 'Costs', 'APA', 'Planning'],
    coverImage: '/images/regions/Monaco.webp',
    coverImageAlt: 'Yachts moored in a harbour in Monaco',
    publishedAt: new Date('2026-07-30T09:00:00Z'),
    content: [
      P("Charter pricing looks opaque from the outside and is actually fairly simple once you see the parts. There are four of them, and only one is fixed when you book."),
      H("1. The base fee"),
      P("This is the headline weekly rate for the yacht and its crew. It is set by size, age, condition, builder reputation and the season, and it varies enormously — a capable weekend motor yacht might be a few thousand a day, while a new 50-metre with a crew of ten in peak August is a six-figure week. Two yachts of the same length can differ by half depending on how recently they were built and refitted."),
      P("The base fee covers the yacht, the full crew and their wages, insurance for the vessel, and normal wear. It does not cover anything you consume during the trip. That is the next part."),
      H("2. The Advance Provisioning Allowance (APA)"),
      P("The APA is a running-cost float, typically 25 to 35 percent of the base fee, that you pay before the charter and the captain draws down during it. It covers fuel, dockage and marina fees, food and drink, port taxes, fuel for the tender and toys, and any special requests."),
      P("This is the part that actually determines whether a charter feels expensive, because how you run the week can swing the APA by a factor of two or more:"),
      L([
        "Fuel is the biggest single variable. A week mostly at anchor with short hops uses a fraction of what a week of long daily passages burns — on a large motor yacht that difference alone can be tens of thousands of euros.",
        "Marina berths in peak season in a marquee port — Monaco, Saint-Tropez, Porto Cervo — can run into four figures a night. Anchoring is free.",
        "Provisioning to a specific standard — particular wines, a chef sourcing premium ingredients daily — adds up quietly across seven days.",
        "Dining ashore at the yacht's expense, if you ask the crew to arrange and settle it, is APA spend too.",
      ]),
      P("Whatever is left in the APA is returned to you at the end of the charter, with an accounting of what was spent. A well-run week often comes back with a meaningful balance. If the APA looks like running short mid-charter, the captain will tell you and ask for a top-up rather than cutting the trip short."),
      H("3. VAT"),
      P("Depending on the flag of the yacht and which country's waters you cruise, VAT applies to the charter fee — commonly in the range of 10 to 22 percent within the EU, with reductions in some jurisdictions for time spent in international waters. Your broker will tell you the applicable rate for your specific itinerary before you commit; it is not a surprise line. A charter that starts outside the EU, or that spends significant time in international waters, can carry a materially lower effective rate — this is worth asking about if the itinerary is flexible."),
      H("4. The crew gratuity"),
      P("Customary, not compulsory, and usually in the region of 5 to 15 percent of the base fee, given to the captain at the end to distribute among the crew. It is genuinely discretionary and tied to the service — a crew that made the week is worth the top of that range. We go into crew and tipping properly in [what to expect from a crewed charter](/blog/what-to-expect-crewed-yacht-charter)."),
      H("Putting it together"),
      P("For a realistic mid-range example: a well-kept 28-metre motor yacht with a crew of five, chartered for a week on the [French Riviera](/yacht-charter/french-riviera) in June, might carry a base fee in the low-to-mid five figures in euros. Add roughly 30 percent APA, the applicable VAT, and a 10 percent gratuity, and the all-in figure is meaningfully above the headline — but a chunk of the APA typically comes back."),
      P("The same yacht in peak August is more. The same week in September is less. A smaller boat is a fraction. A sailing yacht of the same length often runs cheaper both to charter and in APA, because it burns far less fuel. This is why a straight \"what does a charter cost\" question does not have a straight answer until the yacht, the dates and the route are on the table."),
      H("What is not included, and worth budgeting for"),
      L([
        "Getting to and from the yacht — flights, transfers, a hotel night at each end.",
        "Travel insurance that actually covers a charter.",
        "Personal spending ashore that you settle yourself — shopping, a bar tab you pick up, a spa day off the boat.",
        "Any specialist extras you request that the yacht does not carry — a diving instructor and kit, a specific water toy hired in, a private chef flown out for a particular cuisine.",
      ]),
      H("How to keep the total sensible"),
      P("The levers, roughly in order of impact: charter in the shoulder season, choose a slightly older well-refitted yacht over the newest hull, build an itinerary around anchorages rather than marinas, be relaxed about covering distance, and consider a sailing yacht if the group is open to it. None of that compromises the experience — some of it improves it. A quiet week at anchor in June on a well-kept older boat is, for a lot of people, a better holiday than a hectic August week on a new one, and it costs less on every line."),
      P("When you want a real number, the fastest route is to [tell an advisor](/yacht-charter) the group size, the rough dates and the destination, and ask for two or three specific yachts with full cost breakdowns. You can also [browse the fleet](/yacht-charter/all-yachts) to get a feel for what different sizes and ages look like before narrowing down. If you are weighing this against ownership, [we compare the two here](/blog/buying-vs-chartering-a-yacht)."),
    ],
  },
  // 6 ---------------------------------------------------------------
  {
    slug: 'buying-vs-chartering-a-yacht',
    title: 'Buying vs Chartering a Yacht: Which Is Right for You?',
    metaTitle: 'Buying vs Chartering a Yacht: An Honest Comparison',
    metaDescription: 'An honest comparison of buying versus chartering a yacht — the real cost of ownership, the break-even point, and which suits how you actually use a boat.',
    excerpt: 'The maths matters less than one question: how many weeks a year will you genuinely be on board?',
    category: 'Buying a Yacht',
    tags: ['Buying a Yacht', 'Charter Guides', 'Ownership', 'Costs'],
    coverImage: '/images/regions/Sardinia.webp',
    coverImageAlt: 'Motor yachts anchored over clear turquoise water off the Sardinian coast',
    publishedAt: new Date('2026-08-10T09:00:00Z'),
    content: [
      P("This question usually arrives after a few good charters, when someone starts wondering whether they should just buy the boat. It is a reasonable thought, and the answer is genuinely case-by-case, but it turns on one number more than any other: the number of weeks a year you will actually spend aboard."),
      H("The case for chartering"),
      P("When you charter, you pay for the weeks you use and nothing else. There is no berth to pay for in January, no crew salaries running year-round, no winter refit invoice, no depreciation on an asset sitting still for ten months. You also get to change boats — a catamaran in [the Caribbean](/yacht-charter/caribbean) this winter, a 30-metre motor yacht on the [Riviera](/yacht-charter/french-riviera) in June, something bigger for a special occasion — and you get to change your mind."),
      P("For most people who use a yacht two, three, four weeks a year, chartering is simply the correct financial decision, and it is not close. The ownership costs of a comparable yacht over those same weeks would be many times the charter fees. Chartering also means someone else carries every operational headache: a mechanical failure the week before your trip is the fleet's problem, not yours, and you are simply moved to another boat."),
      H("The case for buying"),
      P("Ownership starts to make sense when the usage climbs. If you and your family will genuinely be aboard eight, ten, twelve-plus weeks a year, the per-week economics begin to converge, and the non-financial arguments start to matter more:"),
      L([
        "The boat is set up exactly how you want it, and stays that way — your crew, your provisions, your tender, your art on the walls, your kitchen equipment.",
        "It is available on your schedule, including last-minute, without checking a fleet calendar.",
        "You can leave things aboard between trips, so packing for a week takes an hour, not a day.",
        "A relationship with a permanent crew who know your family, your children's names, how you like the day to run — this compounds over years in a way a series of charters cannot.",
        "A well-chosen yacht, well maintained, holds value reasonably — and can earn charter income in the weeks you are not using it, which offsets a real portion of the running cost.",
      ]),
      P("That last point is important. Many private yachts on the [sale market](/yacht-sale) are also active charter yachts, and a sensible ownership plan often assumes some charter revenue to carry the fixed costs. A yacht that charters ten or twelve weeks a year can cover a large share of its own running costs, though it also means a professionally run, survey-compliant operation and some wear you would not put on a purely private boat."),
      H("The real cost of ownership"),
      P("The rule of thumb the industry uses is that annual running costs — crew, berthing, insurance, maintenance, refit reserve, fuel — come to roughly 10 percent of the yacht's value per year. On a smaller yacht it can be a little less; on a large or older one, more. That is before you account for the purchase price itself and any financing on it."),
      P("Put concretely: a yacht that costs a few million to buy costs a few hundred thousand a year to run whether you use it for two weeks or twenty. Divided across two weeks, that is an expensive fortnight. Divided across fifteen, it looks very different."),
      Q("Buy the boat you will use. The trap is buying the boat you imagine you will use.", "A broker we work with, to every first-time buyer"),
      H("Where people get the decision wrong"),
      P("Almost always by overestimating future usage. The plan is fifteen weeks a year; the reality, once work and school and everything else reassert themselves, is six. The boat then sits, the running costs accrue regardless, and within two or three years the owner is quietly asking a broker about selling. If you are not sure whether your usage will be high, that uncertainty is itself an argument for chartering until it resolves — you lose nothing by waiting, and you learn what you actually want in a boat in the meantime."),
      H("A middle path"),
      P("Fractional and shared ownership programmes exist and can work well for people who want some of the ownership benefits — a familiar boat, a crew who knows them — at a fraction of a share, roughly six to eight weeks of use for a proportional slice of the cost. They are not for everyone, and the good ones are selective, but they are worth knowing about before deciding it is all-or-nothing."),
      H("How to actually decide"),
      P("Be honest about the usage. Look at the last three years — how many weeks did you really spend on a boat, not how many you meant to? If the honest answer is under five and not obviously rising, keep chartering; it is the better deal and the less work. If it is climbing past eight and you find yourself wanting the same boat each time, it is worth [talking to a broker](/yacht-sale) about what ownership would actually look like for the way you cruise. And if you are somewhere in the middle, [a buyer's guide to choosing the right yacht](/blog/buyers-guide-choosing-the-right-yacht) is the sensible next read."),
    ],
  },
  // 7 ---------------------------------------------------------------
  {
    slug: 'buyers-guide-choosing-the-right-yacht',
    title: "A Buyer's Guide to Choosing the Right Yacht",
    metaTitle: "Buyer's Guide: How to Choose the Right Yacht",
    metaDescription: 'How to choose the right yacht to buy — matching size, layout and type to how you actually cruise, and the checks that matter before an offer.',
    excerpt: 'Most buying mistakes are made before the search starts, by deciding on a length instead of describing a use.',
    category: 'Buying a Yacht',
    tags: ['Buying a Yacht', 'Ownership', 'Brokerage'],
    coverImage: '/images/regions/Italy.webp',
    coverImageAlt: 'A superyacht at anchor off Portofino on the Italian Riviera',
    publishedAt: new Date('2026-08-19T09:00:00Z'),
    content: [
      P("The buyers who end up happy are almost always the ones who started by describing how they want to use the boat, in detail, and let that determine the specification. The ones who start with a number — \"something around 30 metres\" — tend to end up with a yacht that is impressive and slightly wrong for them."),
      P("Here is the order the decisions are best made in."),
      H("1. Define the use, concretely"),
      P("Not \"Mediterranean cruising\" but: how many guests, how often, sleeping how many overnight? Long passages or short hops between anchorages? Weeks at anchor or evenings in port? Will it charter when you are not aboard? Warm-water only, or do you want the range and build to go further afield?"),
      P("Every one of those answers pushes the specification in a direction. A boat for six family members doing short Riviera hops and a lot of swimming is a completely different vessel from a boat for twelve doing two-week passages and chartering half the year — even at the same length. Write the brief down. A good broker will push back on it, and that conversation is where the real specification emerges."),
      H("2. Motor, sail or catamaran"),
      P("Motor yachts dominate the market because they suit how most people actually cruise — more interior volume for the length, level decks, and no dependence on wind to keep to a plan. Sailing yachts reward people who want the sailing itself to be part of the point, and can be more economical to run. Catamarans offer enormous deck and interior space for the length, shallow draft, and stability at anchor, at the cost of some marina berthing options and resale liquidity in certain markets. There is no universally right answer, only a right answer for your list from step one."),
      H("3. Size — and the thresholds that matter"),
      P("Length drives cost more than anything, and it is not linear. A few key thresholds change the economics:"),
      L([
        "Around 24 metres, commercial and crew regulations step up, and you generally move from a couple of crew to a professional captain plus crew living aboard.",
        "The larger the yacht, the harder and more expensive peak-season berthing becomes in the marquee ports — a factor if evenings in Monaco or Porto Cervo matter to you.",
        "Above roughly 500 gross tons, a further tier of regulation, crewing and cost applies — this is a bigger step than the extra few metres of length suggests.",
        "Beyond the mid-40s in metres, the yacht is a significant operation with a large permanent crew and running costs to match.",
      ]),
      P("The instinct to size up \"so we don't outgrow it\" is worth resisting unless the usage genuinely justifies it. A slightly smaller yacht used fully beats a larger one used cautiously."),
      H("4. Layout matters more than the brochure length"),
      P("Two yachts of identical length can live completely differently. Things to look at closely: the number and configuration of guest cabins (four equal doubles is a very different boat from a large owner's suite plus three small cabins); whether the main deck has an on-deck master; the size and shade of the outdoor living areas; galley position and whether the crew can serve without walking through guest space; and the tender garage — a boat that launches its tender and toys quickly and dryly is used more than one where it is a production."),
      H("5. Age and condition over badge"),
      P("A five-year-old yacht from a strong builder, well maintained and lightly used, is often a better buy than a new hull — the first depreciation has happened, the systems are proven, and any teething faults have been found and fixed. What matters is maintenance history, not age in isolation. Ask for the full service records, the refit history, the running hours on the main engines and generators, and the survey reports from any previous sale."),
      H("6. The checks before an offer"),
      P("Once a specific yacht is a serious candidate, the acquisition process protects you:"),
      L([
        "A sea trial — the yacht run under way, systems tested under load, by you and a surveyor.",
        "An independent condition survey, hauled out, covering hull, machinery, electrical and safety systems.",
        "A review of the yacht's ownership, flag, VAT status and any outstanding obligations or liens.",
        "For a yacht with charter history, its commercial compliance and survey status.",
      ]),
      P("A broker representing you coordinates all of this, and the findings feed directly into the negotiation — survey issues are routinely reflected in the final price or fixed before closing. We keep this part deliberately structured; [our approach to yacht acquisition](/yacht-sale/french-riviera) walks through what each stage involves."),
      H("7. Think about the exit before you buy"),
      P("The yachts that hold value best are the ones a future buyer will also want: a respected builder, a sensible and popular layout, a documented history, and a size that a lot of the market can operate. A very unusual configuration might be perfect for you and slow to sell later. That is a fine trade to make knowingly; it is a bad one to make by accident."),
      H("8. Budget for the first year honestly"),
      P("The purchase price is the start. The first twelve months of ownership also typically include: any refit or upgrade work the survey flagged or you simply want; kitting the boat out to your standard; the crew's first year; and the running costs at roughly 10 percent of value a year. Going in with a clear-eyed number for all of that, rather than being surprised by it in month three, is the difference between enjoying the boat and resenting it."),
      P("When you are ready to move from thinking to looking, our [yachts for sale on the French Riviera](/yacht-sale/french-riviera) are the current inventory, or [browse the full sale fleet](/yacht-sale/all-yachts). A broker can take your brief from step one and come back with the two or three yachts that actually fit it — [start the conversation here](/yacht-sale). If you have not fully settled the buy-or-charter question, [read this first](/blog/buying-vs-chartering-a-yacht)."),
    ],
  },
  // 8 ---------------------------------------------------------------
  {
    slug: 'what-to-expect-crewed-yacht-charter',
    title: 'What to Expect from a Crewed Yacht Charter',
    metaTitle: 'What to Expect on a Crewed Yacht Charter',
    metaDescription: "A first-timer's guide to a crewed yacht charter — what the crew does, how a day runs, tipping and etiquette, and what is expected of you as a guest.",
    excerpt: 'The best crewed charters feel effortless because a lot of invisible work is going on. Knowing roughly what that is makes you a better guest.',
    category: 'Yachting Advice',
    tags: ['Yachting Advice', 'Charter Guides', 'Crew', 'Etiquette'],
    coverImage: '/assets/crew-onboard.webp',
    coverImageAlt: "A yacht's crew on the dock in front of a motor yacht",
    publishedAt: new Date('2026-08-27T09:00:00Z'),
    content: [
      P("A first crewed charter can be slightly disorienting for people who are used to arranging their own holidays. There is a whole team whose job is to look after you, and the instinct is either to over-direct them or to feel awkward asking for anything. Neither is necessary. Here is roughly how it works."),
      H("Who is aboard"),
      P("On a yacht up to the high 20s in metres, the crew is typically three to five people:"),
      L([
        "The captain — responsible for the yacht, the safety of everyone aboard, and the route. Also the person you plan the week with.",
        "A chef — cooks every meal to your preferences, adjusts to allergies and requests, and provisions along the way.",
        "One or two stewardesses — the interior, the service, the cabins, the drinks, the detail.",
        "A deckhand or first mate — the exterior, the tender, the water toys, and keeping the yacht immaculate.",
      ]),
      P("Larger yachts add more of each, plus specialists — a dedicated bosun, a masseuse, a second chef, a dive instructor. Smaller weekend boats might run with a captain and one crew, or a captain alone."),
      H("Before you arrive: the preference sheet"),
      P("A week or two ahead, you will be asked to fill in a preference sheet. Treat it seriously — it is the single biggest lever you have on how tailored the week feels. It covers food likes and dislikes for each guest, allergies, favourite drinks and wines, dietary requirements, how you like breakfast, whether you want a formal dinner or a barefoot one, celebrations and their dates, activity interests, and what a perfect day looks like. A chef who knows in advance that one guest is coeliac and another cannot stand coriander has provisioned around it before you step aboard."),
      H("How a day runs"),
      P("There is no fixed schedule, and that is the point. A typical day: the crew are up early, the yacht is cleaned and prepped before you wake, breakfast appears when you appear. Over coffee the captain talks through options for the day based on the weather — a bay here, a town there, a longer passage or a short one. You choose, or you leave it to them."),
      P("Then the day unfolds: a passage, an anchorage, swimming, the water toys, lunch aboard, a slow afternoon, maybe a move to a second spot, dinner aboard or a tender ashore to a restaurant the crew booked. The crew read the mood — a lively group gets the music and the toys out, a quiet one gets left alone with a book. Good crew are very good at this."),
      H("What is expected of you"),
      P("Not much, and mostly common courtesy. A few things genuinely help:"),
      L([
        "Send the preferences ahead, and be specific. Vague answers get vague results.",
        "Take shoes off when boarding — teak decks and hard soles do not mix.",
        "Be roughly predictable about meal timing where you can, or just tell the chef when plans change. They can flex, but a heads-up helps.",
        "Treat the crew's cabins and the crew mess as theirs. They live aboard, and it is the one part of the boat that is not yours for the week.",
        "Keep an eye on water and, on smaller yachts, power — long showers by eight people add up, and the crew would rather you knew than ran the watermaker flat out all day.",
      ]),
      H("Tipping"),
      P("A gratuity at the end is customary — commonly 5 to 15 percent of the charter fee, given to the captain to share among the crew, adjusted for how the week went. It is discretionary and tied to service. If the crew made the trip, the top of that range is normal and deserved. It is given privately, usually on the last evening or morning, in cash or by transfer, to the captain directly."),
      H("Privacy, and the small awkwardness of it"),
      P("People sometimes worry about having crew around all week. In practice it resolves quickly. Professional crew are practised at being present when needed and invisible when not — they will not be in the salon when you want the salon, and they retreat to the crew areas in the evening once service is done. Within a day or two most guests stop noticing, and by the end of the week the goodbye is often genuinely a little sad."),
      H("The thing people underestimate"),
      P("How much the crew shapes the week. Two charters on the same yacht in the same waters with different crews are different holidays. A captain who knows a coastline finds the anchorage that is empty when everywhere else is full; a chef who has understood your table turns dinner into the best part of the day; a deckhand who is genuinely good with kids changes a family trip entirely."),
      P("This is why matching the crew to the guests matters as much as matching the yacht, and why it is worth telling your advisor about the group honestly — not just the numbers. If you are still deciding on a destination, [our French Riviera charter guide](/blog/french-riviera-yacht-charter-guide) and the [bespoke experiences](/experiences) the team arranges around a charter are good next reads. When you are ready, [start with the fleet](/yacht-charter)."),
    ],
  },
  // 9 ---------------------------------------------------------------
  {
    slug: 'best-time-charter-yacht-mediterranean',
    title: 'The Best Time to Charter a Yacht in the Mediterranean',
    metaTitle: 'Best Time to Charter a Yacht in the Mediterranean',
    metaDescription: 'Month by month, the best time to charter a yacht in the Mediterranean — weather, crowds and price across the Riviera, Italy, Corsica, Sardinia and Greece.',
    excerpt: 'Everyone wants August and then complains about the crowds. The people who know book June or September.',
    category: 'Charter Guides',
    tags: ['Charter Guides', 'Mediterranean', 'Seasons', 'Planning'],
    coverImage: '/images/regions/Corsica.webp',
    coverImageAlt: 'Yachts moored in the harbour at Ajaccio, Corsica',
    publishedAt: new Date('2026-09-02T09:00:00Z'),
    content: [
      P("The Mediterranean charter season is May to October, and within it there is a clear pattern: the weather is good throughout, the water warms as the summer goes on, and the crowds and prices peak hard in a narrow window around August. The skill is in matching the month to what you want, and to which part of the sea."),
      H("May: early, quiet, cooler water"),
      P("The coast is green, the light is beautiful, the anchorages are almost empty, and prices are at their lowest. The water is still cool — swimming is brisk rather than blissful — and the weather is slightly less settled than midsummer. Best for people who care more about the coastline and the calm than about long swims. One caveat: the [Cannes](/yacht-charter/french-riviera/cannes) Film Festival in mid-May distorts the whole western Riviera for a fortnight, and the Monaco Grand Prix does the same in late May."),
      H("June: the connoisseur's month"),
      P("Arguably the best all-round window. Long days, warm and settled weather, water that is properly swimmable by mid-month, and the anchorages still uncontested because the school holidays have not started. Prices are below peak. If someone asks us for one month, it is usually this one."),
      H("July: high summer begins"),
      P("Hot, reliable, and busy. The popular bays fill by mid-morning and the marquee ports need booking well ahead. Still an excellent time to be on the water — you just plan around the crowds, anchor early, and eat aboard more. In [Greece](/yacht-charter/greece), the Cyclades meltemi wind is building and itineraries need slack."),
      H("August: peak everything"),
      P("Warmest water, longest track record of sunshine, and the busiest and most expensive fortnight of the European season, especially the two weeks around the 15th. Every restaurant ashore is booked, [Saint-Tropez](/yacht-charter/french-riviera/saint-tropez) and Porto Cervo are a scene, and berths are at a premium. If your dates are fixed by school holidays, August works — with a captain who knows the quiet anchorages it is still wonderful. If your dates are flexible, this is the month to avoid."),
      H("September: the quiet reward"),
      P("The sea holds its August temperature well into the month, the crowds evaporate after the first week, restaurants have tables again, and prices come down. The weather is settled and warm. For a couple, or anyone without children in school, September is the best-value great month of the year — a close rival to June, with warmer water."),
      H("October: the tail"),
      P("The season winds down. Early October can still be excellent, especially in the southern Mediterranean — [Sardinia](/yacht-charter/sardinia), Sicily, the southern [Italian](/yacht-charter/italy) coast — where the water stays warm longest. By late October most yachts are preparing to cross to the Caribbean and the fleet thins out."),
      H("Events that move the calendar"),
      P("A handful of fixed dates distort prices and availability far beyond their own week, and it is worth knowing them whether you want to be there or well away. The Cannes Film Festival and the Monaco Grand Prix, both in May, book out the entire western Riviera. The Cannes and Monaco yacht shows in September do the same in early autumn. In Sardinia, the weeks around the Maxi Yacht Rolex Cup in Porto Cervo in early September are the busiest of the local season. If your trip is near any of these, decide deliberately: the atmosphere is extraordinary, but so is the premium, and the anchorages are full."),
      H("A note on water temperature"),
      P("The sea lags the air by about two months. It is coldest in March, not January, and warmest in late August into September — which is the real reason September swimming is so good despite the shorter days. In practical terms: May and early June water is bracing (18–20°C), July is comfortable (22–24°C), and August through mid-September is genuinely warm (25°C and up). If long, lazy swims are central to the trip, weight your dates toward the back half of the season."),
      H("Matching the month to the region"),
      P("The pattern shifts as you move around the sea. The [French Riviera](/yacht-charter/french-riviera) and [Corsica](/yacht-charter/corsica) are at their best from June to September. The Greek Cyclades are more comfortable in the shoulder months when the meltemi is weaker; the Ionian is good all summer. The [Balearics](/yacht-charter/balearic-islands) follow the Riviera pattern closely. The southern Mediterranean — Sicily, southern Sardinia — extends the good swimming a few weeks later into autumn than the north."),
      H("Book earlier than you think"),
      P("The best yachts for July and August are often reserved by the previous winter, and the very best are held by repeat clients before they reach the open market at all. If your dates are fixed — school holidays, an anniversary week — start the search six to nine months out. Shoulder-season weeks in June and September have more give, and a good boat can sometimes be found a couple of months ahead, but the principle holds: the earlier you look, the better the choice."),
      Q("There is no bad month between June and September. There is only the month that fits what you want, and the one that doesn't.", "Our charter team"),
      P("If your dates are flexible at all, tell an advisor the window you are considering and the destination, and ask what each month would actually be like — the honest version, crowds and all. [Start here](/yacht-charter), or read [our guide to what a week on the Riviera looks like](/blog/french-riviera-yacht-charter-guide) for a sense of how the days come together."),
    ],
  },
  // 10 --------------------------------------------------------------
  {
    slug: 'planning-family-yacht-charter',
    title: 'Planning a Family Yacht Charter: Tips for a Smooth Trip',
    metaTitle: 'Family Yacht Charter: Tips for a Smooth Trip',
    metaDescription: 'Practical advice for a family yacht charter — choosing the right boat and route for children, keeping everyone happy aboard, and what to tell the crew.',
    excerpt: 'A family charter lives or dies on two things: the right boat for the ages aboard, and a route that never makes the day feel long.',
    category: 'Yachting Advice',
    tags: ['Yachting Advice', 'Family', 'Charter Guides', 'Planning'],
    coverImage: '/images/regions/Balearic_Islands.webp',
    coverImageAlt: 'A yacht anchored in a sheltered cove below cliffs in the Balearic Islands',
    publishedAt: new Date('2026-09-08T09:00:00Z'),
    content: [
      P("Family charters are among the most rewarding weeks a yacht can produce and among the easiest to get slightly wrong. The mistakes are nearly always the same two: a boat that does not quite suit the ages aboard, and an itinerary built for adults that leaves the children restless. Both are avoidable."),
      H("Choosing the boat"),
      P("For a family, deck space and shade matter more than a headline length. Children live outside, and you want room for them to be outside safely — a wide swim platform, a shaded aft deck for meals and downtime, and a foredeck that is comfortable rather than an afterthought."),
      P("Catamarans are popular with families for exactly this reason: enormous deck area for the length, a stable platform that reduces seasickness worries, shallow draft that gets you into calmer, shallower bays, and steps to the water that a three-year-old can manage. Motor yachts work too, especially for teenagers and for families who want more separation between cabins — just look hard at the outdoor living space, not just the salon."),
      P("Cabin layout is the other thing to check. Young children usually want to be near their parents; teenagers usually want to be as far away as the boat allows. A yacht where the guest cabins are all clustered together suits one and not the other. Bunk cabins, where a boat has them, are often a hit with children who would happily share and free up a double for grandparents."),
      H("The water toys question"),
      P("Ask specifically what the yacht carries and match it to the ages. A towable ring and a jet ski are brilliant for confident eight-to-fifteen-year-olds and useless or frightening for a toddler. What matters for the youngest is a shaded, netted swim area or a large inflatable platform off the back, a paddleboard steady enough to sit on, and snorkelling kit in child sizes. A slide off the top deck is the single most reliable source of joy on a family charter, and plenty of boats have one — it is worth asking."),
      H("Building the route"),
      P("The single best piece of advice for a family charter: keep the passages short. An hour or two between anchorages, not five. A long day under way is where children get bored and adults get stressed, and it is almost never necessary — every good Mediterranean cruising ground has enough anchorages close together that you can move a little and arrive somewhere new."),
      P("Anchor for swimming by mid-morning, so the best hours are spent in the water rather than getting there. Plan the moving for the early afternoon lull when younger children might nap anyway. Keep one \"nothing\" day where the boat does not move at all — it is often the day everyone remembers."),
      P("Destinations that suit this rhythm well: the Ionian islands in [Greece](/yacht-charter/greece), where everything is close and the water is calm; the [French Riviera](/yacht-charter/french-riviera) with its short hops and its beaches; the [Balearics](/yacht-charter/balearic-islands); and [Sardinia's](/yacht-charter/sardinia) sheltered northern coast. The open Cyclades, with their wind and long passages, are a harder sell with young children aboard."),
      H("What to tell the crew"),
      P("Everything, and early. The ages of the children, how confident they are in the water, what they eat and what they absolutely will not eat, nap times, allergies, whether anyone gets seasick, and what a good day looks like for each of them. A crew that knows a seven-year-old is obsessed with the inflatable slide and will not touch anything green has a much better chance of making the week work."),
      P("Ask specifically whether the crew are comfortable and experienced with children — most are, and a deckhand who is genuinely good with kids is worth their weight. Some yachts can arrange a dedicated nanny or a childcare-trained stewardess for the week; if you want an evening ashore as adults, ask about this early, as it usually needs booking."),
      H("Seasickness, briefly"),
      P("Most family cruising grounds are chosen partly for calm water, so it is rarely an issue. If someone in the family is prone to it, mention it — the crew will plan passages for the calmest part of the day, keep them on deck looking at the horizon rather than below, and have the usual remedies aboard. A catamaran or a larger motor yacht both help. It almost always settles after the first day or two."),
      H("Safety, briefly"),
      P("A good crew briefs the whole family on day one — where to hold on, which areas are off-limits under way, life jackets for non-swimmers on deck and in the tender. Life jackets sized for children should be aboard; confirm this before you charter if you have small ones. After the first day it fades into the background, as it should."),
      H("The payoff"),
      P("Done well, a family charter is the rare holiday where the children are outdoors and busy from breakfast to dusk, the adults actually relax because someone else is cooking and cleaning and watching the weather, and everyone eats dinner together every night because there is nowhere else to be. That is worth planning for properly."),
      P("Tell an advisor the ages aboard and roughly when you want to go, and ask for boats and routes chosen with that in mind — not just adapted from an adult itinerary. [Start with the charter fleet](/yacht-charter), or see the [bespoke experiences](/experiences) the team can build around a family week."),
    ],
  },
]

async function main() {
  for (const post of posts) {
    const data = {
      ...post,
      readingMinutes: readingMinutes(post.content),
      status: 'published',
    }
    const saved = await prisma.yachtingBlogPost.upsert({
      where: { slug: post.slug },
      create: data,
      update: data,
    })
    console.log(`✓ ${saved.id}  /blog/${saved.slug}  (${saved.readingMinutes} min)`)
  }
  const total = await prisma.yachtingBlogPost.count()
  console.log(`\nyachting_blog_post now holds ${total} rows.`)
}

main()
  .catch((e) => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())
