ALTER TABLE "reservation"
  ADD COLUMN IF NOT EXISTS "start_time" TEXT,
  ADD COLUMN IF NOT EXISTS "end_time" TEXT,
  ADD COLUMN IF NOT EXISTS "planned_itinerary" TEXT,
  ADD COLUMN IF NOT EXISTS "deposit" DOUBLE PRECISION DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "payment_deadline" TIMESTAMP(3) DEFAULT now();

ALTER TABLE "contract"
  ADD COLUMN IF NOT EXISTS "number_of_guests" INTEGER,
  ADD COLUMN IF NOT EXISTS "planned_itinerary" TEXT,
  ADD COLUMN IF NOT EXISTS "deposit" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "payment_deadline" TIMESTAMP(3);
