-- CreateTable
CREATE TABLE "destination" (
    "id" SERIAL NOT NULL,
    "region_slug" TEXT NOT NULL,
    "city_slug" TEXT,
    "name" TEXT NOT NULL,
    "region" TEXT NOT NULL,
    "city" TEXT,
    "title" TEXT NOT NULL,
    "meta_description" TEXT NOT NULL,
    "h1" TEXT NOT NULL,
    "hero_image" TEXT NOT NULL,
    "eyebrow" TEXT NOT NULL,
    "intro" TEXT[],
    "related_keys" TEXT[],
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "destination_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "destination_faq" (
    "id" SERIAL NOT NULL,
    "destination_id" INTEGER NOT NULL,
    "question" TEXT NOT NULL,
    "answer" TEXT NOT NULL,
    "position" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "destination_faq_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "destination_itinerary" (
    "id" SERIAL NOT NULL,
    "destination_id" INTEGER NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "position" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "destination_itinerary_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "destination_region_slug_city_slug_key" ON "destination"("region_slug", "city_slug");

-- CreateIndex
CREATE INDEX "destination_faq_destination_id_idx" ON "destination_faq"("destination_id");

-- CreateIndex
CREATE INDEX "destination_itinerary_destination_id_idx" ON "destination_itinerary"("destination_id");

-- AddForeignKey
ALTER TABLE "destination_faq" ADD CONSTRAINT "destination_faq_destination_id_fkey" FOREIGN KEY ("destination_id") REFERENCES "destination"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "destination_itinerary" ADD CONSTRAINT "destination_itinerary_destination_id_fkey" FOREIGN KEY ("destination_id") REFERENCES "destination"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- Seed destination + destination_faq + destination_itinerary from the
-- previously hardcoded lib/destinations.ts catalogue (21 entries), copied
-- verbatim — no copy rewritten. updated_at backfilled to now() since the
-- column has no default and this is the initial import.

INSERT INTO "destination" ("id", "region_slug", "city_slug", "name", "region", "city", "title", "meta_description", "h1", "hero_image", "eyebrow", "intro", "related_keys", "updated_at") VALUES
(1, 'french-riviera', 'cannes', 'Cannes', 'French Riviera', 'Cannes', 'Luxury Yacht Charter Cannes | Private Yacht Rental | Syrama Yachting', 'Charter a luxury yacht in Cannes with Syrama Yachting. Browse our curated fleet available on the Croisette and book a private cruise to the Lérins Islands, Antibes or Saint-Tropez.', 'Luxury Yacht Charter in Cannes', '/images/regions/French_Riviera.webp', 'French Riviera', ARRAY['Cannes is one of the most iconic ports of call on the French Riviera, known worldwide for the Croisette, the Cannes Film Festival and its position at the heart of the Bay of Cannes. Chartering a yacht here puts you minutes from open water, with the Lérins Islands, Antibes and Saint-Tropez all within easy reach for a day trip or a multi-day cruise.', 'Syrama Yachting works with a curated fleet of yachts based in and around Cannes, from sleek day boats for a Croisette-to-Lérins afternoon to larger crewed yachts for a week along the Riviera. Whatever the occasion, our team arranges the crew, provisioning and itinerary around you.'], ARRAY[]::text[], now()),
(2, 'french-riviera', 'saint-tropez', 'Saint-Tropez', 'French Riviera', 'Saint-Tropez', 'Luxury Yacht Charter Saint-Tropez | Private Yacht Rental | Syrama Yachting', 'Charter a luxury yacht in Saint-Tropez with Syrama Yachting. Explore the Gulf of Saint-Tropez, Pampelonne beach and the Var coastline aboard our curated fleet.', 'Luxury Yacht Charter in Saint-Tropez', '/images/regions/French_Riviera.webp', 'French Riviera', ARRAY['Saint-Tropez remains the most glamorous harbour on the French Riviera, its old port lined with yachts beneath the Provençal rooftops of the village. Just outside the harbour, the Gulf of Saint-Tropez opens onto some of the clearest anchorages on this coast, from Pampelonne beach to the quieter coves toward Cap Camarat.', 'Our Saint-Tropez fleet ranges from agile day yachts for a beach-club afternoon to larger vessels for a week exploring the Var coastline and beyond. Syrama Yachting''s team handles the booking, crew and itinerary planning around your dates.'], ARRAY[]::text[], now()),
(3, 'french-riviera', 'monaco', 'Monaco', 'French Riviera', 'Monaco', 'Luxury Yacht Charter Monaco | Private Yacht Rental | Syrama Yachting', 'Charter a luxury yacht in Monaco with Syrama Yachting. Depart from Port Hercules for Cap Ferrat, Menton or the Italian Riviera aboard our curated fleet.', 'Luxury Yacht Charter in Monaco', '/images/regions/Monaco.webp', 'French Riviera', ARRAY['Monaco''s Port Hercules sits at the eastern edge of the French Riviera, within sight of Monte-Carlo and a short sail from Cap Ferrat, Beaulieu-sur-Mer and Menton toward the Italian border. It''s one of the most convenient departure points on the coast, equally suited to a private day at sea or the start of a longer Riviera itinerary.', 'Syrama Yachting arranges charters departing from Monaco across a fleet ranging from day boats to larger crewed yachts, with the team coordinating crew, provisioning and itinerary for your dates.'], ARRAY[]::text[], now()),
(4, 'french-riviera', 'juan-les-pins', 'Juan-les-Pins', 'French Riviera', 'Juan-les-Pins', 'Luxury Yacht Charter Juan-les-Pins | Private Yacht Rental | Syrama Yachting', 'Charter a luxury yacht in Juan-les-Pins with Syrama Yachting. Depart the Golfe-Juan bay for Cap d''Antibes, the Lérins Islands or Cannes aboard our curated fleet.', 'Luxury Yacht Charter in Juan-les-Pins', '/images/regions/French_Riviera.webp', 'French Riviera', ARRAY['Juan-les-Pins sits on the sheltered Golfe-Juan bay at the base of Cap d''Antibes, known for its sandy beaches, beach clubs and a jazz festival that has drawn musicians to the pine-lined seafront since the 1960s. Its calm, protected water makes it an easy departure point, with Cap d''Antibes, the Lérins Islands and Cannes all within a short run.', 'Syrama Yachting arranges charters departing from Juan-les-Pins, with the fleet, crew and itinerary built around your dates — from a beach-club afternoon to a longer cruise along the Riviera.'], ARRAY[]::text[], now()),
(5, 'french-riviera', 'beaulieu-sur-mer', 'Beaulieu-sur-Mer', 'French Riviera', 'Beaulieu', 'Luxury Yacht Charter Beaulieu-sur-Mer | Private Yacht Rental | Syrama Yachting', 'Charter a luxury yacht in Beaulieu-sur-Mer with Syrama Yachting. Depart this sheltered bay near Cap Ferrat for Monaco, Nice or the Italian border aboard our curated fleet.', 'Luxury Yacht Charter in Beaulieu-sur-Mer', '/images/regions/French_Riviera.webp', 'French Riviera', ARRAY['Beaulieu-sur-Mer is one of the most sheltered bays on the French Riviera, tucked beneath the hills between Nice and Cap Ferrat — locals have long called its microclimate "la petite Afrique." Its Belle Époque villas, including the Villa Kérylos, and calm anchorage make it a quieter alternative to Nice or Monaco, both a short cruise away.', 'Syrama Yachting arranges charters departing from Beaulieu-sur-Mer, with the fleet, crew and itinerary built around your dates — an easy base for exploring the eastern Riviera and the Italian border beyond.'], ARRAY[]::text[], now()),
(6, 'french-riviera', 'saint-jean-cap-ferrat', 'Saint-Jean-Cap-Ferrat', 'French Riviera', 'Saint-Jean-Cap-Ferrat', 'Luxury Yacht Charter Saint-Jean-Cap-Ferrat | Private Yacht Rental | Syrama Yachting', 'Charter a luxury yacht in Saint-Jean-Cap-Ferrat with Syrama Yachting. Cruise past the peninsula''s villas, Villa Ephrussi de Rothschild and on to Monaco or Nice.', 'Luxury Yacht Charter in Saint-Jean-Cap-Ferrat', '/images/regions/French_Riviera.webp', 'French Riviera', ARRAY['Saint-Jean-Cap-Ferrat is a narrow, pine-covered peninsula between Nice and Monaco, long known for some of the most expensive real estate anywhere in the world and for the Villa Ephrussi de Rothschild, its gardens visible from the water. The coastline circling the cape is one of the most scenic short cruises on the Riviera, with sheltered coves on either side.', 'Syrama Yachting arranges charters departing from and around Cap Ferrat, with the fleet, crew and itinerary built around your dates — a natural base between Nice, Beaulieu and Monaco.'], ARRAY[]::text[], now()),
(7, 'french-riviera', 'menton', 'Menton', 'French Riviera', 'Menton', 'Luxury Yacht Charter Menton | Private Yacht Rental | Syrama Yachting', 'Charter a luxury yacht in Menton with Syrama Yachting. Cruise the last French port before Italy, with the Italian Riviera and Monaco both within easy reach.', 'Luxury Yacht Charter in Menton', '/images/regions/French_Riviera.webp', 'French Riviera', ARRAY['Menton is the last French town before the Italian border, known for its Belle Époque architecture, sheltered microclimate and the lemons its annual Fête du Citron celebrates every February. Its position puts the Italian Riviera — Ventimiglia, Bordighera, San Remo — within a short cruise, alongside Monaco and Cap Martin back toward the rest of the French coast.', 'Syrama Yachting arranges charters departing from Menton, with the fleet, crew and itinerary built around your dates — a natural base for exploring both the French and Italian Rivieras in one trip.'], ARRAY[]::text[], now()),
(8, 'french-riviera', 'golfe-juan', 'Golfe-Juan', 'French Riviera', 'Golfe Juan', 'Luxury Yacht Charter Golfe-Juan | Private Yacht Rental | Syrama Yachting', 'Charter a luxury yacht in Golfe-Juan with Syrama Yachting. Depart this historic bay between Cannes and Antibes for the Lérins Islands or Cap d''Antibes.', 'Luxury Yacht Charter in Golfe-Juan', '/images/regions/French_Riviera.webp', 'French Riviera', ARRAY['Golfe-Juan sits in the sheltered bay between Cannes and Antibes, best known historically as the spot where Napoleon landed in 1815 on his return from Elba. Today it''s a quieter, more low-key harbour town than its neighbours, with the same easy access to the Lérins Islands, Cap d''Antibes and Cannes.', 'Syrama Yachting arranges charters departing from Golfe-Juan, with the fleet, crew and itinerary built around your dates — a calmer alternative departure point for the same stretch of coast.'], ARRAY[]::text[], now()),
(9, 'french-riviera', 'saint-raphael', 'Saint-Raphaël', 'French Riviera', 'Saint-Raphaël', 'Luxury Yacht Charter Saint-Raphaël | Private Yacht Rental | Syrama Yachting', 'Charter a luxury yacht in Saint-Raphaël with Syrama Yachting. Depart beneath the red Esterel cliffs for the Gulf of Saint-Tropez or Cannes aboard our fleet.', 'Luxury Yacht Charter in Saint-Raphaël', '/images/regions/French_Riviera.webp', 'French Riviera', ARRAY['Saint-Raphaël sits on the Var coast beneath the red porphyry cliffs of the Massif de l''Estérel, a distinctive stretch of coastline unlike anywhere else on the Riviera. It''s a natural, less crowded departure point on the western approach to the Gulf of Saint-Tropez, with Cannes and the Lérins Islands reachable in the other direction.', 'Syrama Yachting arranges charters departing from Saint-Raphaël, with the fleet, crew and itinerary built around your dates — from a coastal cruise along the Estérel cliffs to a full day across the Gulf of Saint-Tropez.'], ARRAY[]::text[], now()),
(10, 'french-riviera', 'nice', 'Nice', 'French Riviera', 'Nice', 'Luxury Yacht Charter Nice | Private Yacht Rental | Syrama Yachting', 'Charter a luxury yacht in Nice with Syrama Yachting. Depart the Baie des Anges, capital of the French Riviera, for Cap Ferrat, Monaco or Cannes.', 'Luxury Yacht Charter in Nice', '/images/regions/French_Riviera.webp', 'French Riviera', ARRAY['Nice is the capital of the French Riviera, its curved Baie des Anges framed by the Promenade des Anglais on one side and Mont Boron on the other. As the coast''s largest city and main international gateway, it puts Cap Ferrat, Beaulieu and Monaco within a short cruise east, and Antibes and Cannes within reach to the west.', 'Our Nice fleet is smaller than our Cannes or Saint-Tropez selection, so availability is more limited — but Syrama Yachting can still arrange a charter departing from Nice, with the crew and itinerary built around your dates, and can suggest a nearby departure point on the same coast if nothing currently based here suits.'], ARRAY[]::text[], now()),
(11, 'french-riviera', 'antibes', 'Antibes', 'French Riviera', 'Antibes', 'Luxury Yacht Charter Antibes | Private Yacht Rental | Syrama Yachting', 'Charter a luxury yacht in Antibes with Syrama Yachting. Depart Port Vauban, Europe''s largest yachting harbour, for the Lérins Islands, Cannes or Cap d''Antibes.', 'Luxury Yacht Charter in Antibes', '/images/regions/French_Riviera.webp', 'French Riviera', ARRAY['Antibes is home to Port Vauban, the largest yachting harbour in Europe, set beneath the ramparts of its old town and the Picasso Museum in the former Château Grimaldi. The wooded Cap d''Antibes peninsula extends south of the town, with the Lérins Islands and Cannes a short run in one direction and Juan-les-Pins in the other.', 'Our Antibes fleet is smaller than our Cannes or Saint-Tropez selection, so availability is more limited — but Syrama Yachting can still arrange a charter departing from Antibes, with the crew and itinerary built around your dates, and can suggest a nearby departure point on the same coast if nothing currently based here suits.'], ARRAY[]::text[], now()),
(12, 'emirates', 'dubai', 'Dubai', 'Emirates', 'Dubai', 'Luxury Yacht Charter Dubai | Private Yacht Rental | Syrama Yachting', 'Charter a luxury yacht in Dubai with Syrama Yachting. Cruise past Dubai Marina, Palm Jumeirah and the Burj Al Arab aboard our curated fleet on the Arabian Gulf.', 'Luxury Yacht Charter in Dubai', '/images/regions/Dubai.webp', 'Emirates', ARRAY['Dubai offers one of the most striking skylines to cruise past anywhere in the world, from Dubai Marina and Palm Jumeirah to the Burj Al Arab along the Arabian Gulf coastline. Charters here run year-round, with warm waters and calm conditions for most of the season.', 'Syrama Yachting''s Dubai fleet covers everything from a few hours on the water to a full-day charter, with departures typically from Dubai Marina and hourly or daily rates depending on the yacht.'], ARRAY[]::text[], now()),
(13, 'french-riviera', NULL, 'French Riviera', 'French Riviera', NULL, 'Luxury Yacht Charter French Riviera | Syrama Yachting', 'Charter a luxury yacht on the French Riviera with Syrama Yachting. Browse our full fleet across Cannes, Saint-Tropez, Monaco and the wider Côte d''Azur.', 'Luxury Yacht Charter on the French Riviera', '/images/regions/French_Riviera.webp', 'Côte d''Azur', ARRAY['The French Riviera — the Côte d''Azur — is the Mediterranean coastline stretching from Saint-Tropez to Menton at the Italian border, taking in Cannes, Antibes, Nice and Monaco along the way. It remains the reference destination for yacht charter in Europe, with a dense network of marinas, anchorages and coastal towns within a day''s sail of one another.', 'Syrama Yachting curates a fleet across the Riviera''s main ports, from Cannes and Saint-Tropez to Monaco and the smaller harbours between them, so an itinerary can move between destinations rather than staying fixed to a single port.'], ARRAY['corsica'], now()),
(14, 'balearic-islands', NULL, 'Balearic Islands', 'Balearic Islands', NULL, 'Luxury Yacht Charter Balearic Islands | Syrama Yachting', 'Charter a luxury yacht in the Balearic Islands with Syrama Yachting. From Ibiza''s coves to the quiet calas of Formentera and Mallorca, cruise the western Mediterranean in style.', 'Luxury Yacht Charter in the Balearic Islands', '/images/regions/Balearic_Islands.webp', 'Spain', ARRAY['Scattered across the western Mediterranean off Spain''s eastern coast, the Balearic archipelago packs an outsized range of moods into a handful of islands: Ibiza''s legendary sunset coastline and Dalt Vila old town, Mallorca''s deep bays and the Serra de Tramuntana mountains, and the shallow, almost impossibly turquoise waters of Formentera to the south. Quieter Menorca, a UNESCO biosphere reserve, rounds out an archipelago built for island-hopping by water rather than road.', 'Syrama Yachting curates a fleet for charter across the Balearics, so a week on the water can move freely between islands — an afternoon anchored off Formentera, a night in Ibiza Town, a run along Mallorca''s northern coast — with the crew and itinerary arranged around your dates.'], ARRAY['french-riviera', 'italy'], now()),
(15, 'greece', NULL, 'Greece', 'Greece', NULL, 'Luxury Yacht Charter Greece | Syrama Yachting', 'Charter a luxury yacht in Greece with Syrama Yachting. Island-hop the Cyclades — Mykonos, Santorini, Paros — or the Ionian Sea aboard a curated fleet built for it.', 'Luxury Yacht Charter in Greece', '/images/regions/Greece.webp', 'Aegean & Ionian Seas', ARRAY['Few coastlines reward a yacht the way Greece does. Thousands of islands and a coastline longer than most countries'' entire borders mean an itinerary here is rarely about one destination — it''s about the sequence: a whitewashed hillside in Santorini, a beach club afternoon in Mykonos, a quiet anchorage in the Ionian that never makes it onto a ferry route. The meltemi wind that shapes Aegean sailing in high summer is as much a part of the experience as the islands themselves.', 'Syrama Yachting arranges charters across Greek waters, from the Cyclades to the Ionian and the Sporades, with the fleet, crew and route built around how long you have and which islands you actually want to see.'], ARRAY['italy', 'french-riviera'], now()),
(16, 'italy', NULL, 'Italy', 'Italy', NULL, 'Luxury Yacht Charter Italy | Syrama Yachting', 'Charter a luxury yacht in Italy with Syrama Yachting. Cruise the Amalfi Coast, Capri and Sicily, or the Ligurian coastline around Portofino, aboard a curated fleet.', 'Luxury Yacht Charter in Italy', '/images/regions/Italy.webp', 'Mediterranean', ARRAY['Italy''s coastline does most of the work for you: the pastel cliffs of the Amalfi Coast, the sheer rock faces of Capri, the pale-pink harbour of Portofino on the Ligurian coast, and further south, the Aeolian Islands off Sicily with their black-sand beaches and still-active volcano at Stromboli. Few countries pack this much coastline personality into a single charter.', 'Syrama Yachting arranges charters across Italian waters, from the Tyrrhenian coast around Naples and the Amalfi Coast to Liguria in the north and the Aeolian Islands further south, with the crew and itinerary built around your dates.'], ARRAY['sardinia', 'corsica', 'greece'], now()),
(17, 'corsica', NULL, 'Corsica', 'Corsica', NULL, 'Luxury Yacht Charter Corsica | Syrama Yachting', 'Charter a luxury yacht in Corsica with Syrama Yachting. Explore Bonifacio''s clifftop citadel, Porto-Vecchio and the Scandola nature reserve aboard a curated fleet.', 'Luxury Yacht Charter in Corsica', '/images/regions/Corsica.webp', 'L''Île de Beauté', ARRAY['Corsica earned the nickname "L''Île de Beauté" honestly — granite cliffs dropping straight into the water, the clifftop citadel of Bonifacio, and the Scandola Nature Reserve, a UNESCO World Heritage site accessible only by boat. Closer to the Italian coast than to mainland France, the island sits at the crossing point between the French Riviera, Sardinia and the wider western Mediterranean.', 'Syrama Yachting arranges charters around Corsica, from Bonifacio in the south to Calvi in the north, with itineraries that can extend across the strait to Sardinia or back toward the French Riviera depending on how long you have.'], ARRAY['sardinia', 'french-riviera', 'italy'], now()),
(18, 'maldives', NULL, 'Maldives', 'Maldives', NULL, 'Luxury Yacht Charter Maldives | Syrama Yachting', 'Charter a luxury yacht in the Maldives with Syrama Yachting. Cruise between atolls in the Indian Ocean aboard a curated fleet, with warm water and calm conditions year-round.', 'Luxury Yacht Charter in the Maldives', '/images/regions/Maldives.webp', 'Indian Ocean', ARRAY['The Maldives is a different kind of charter altogether — roughly 1,200 coral islands spread across 26 atolls in the Indian Ocean, with no real "coastline" to follow so much as a scatter of reefs, lagoons and sandbanks to move between. It runs on its own calendar too: the dry, north-east monsoon season from November to April is the classic window, well outside the Mediterranean summer that shapes charter timing everywhere else on this list.', 'Syrama Yachting arranges charters across the Maldivian atolls, with the crew handling navigation between islands that often have no fixed address beyond their atoll — a genuinely different charter experience from a European coastline.'], ARRAY[]::text[], now()),
(19, 'caribbean', NULL, 'Caribbean', 'Caribbean', NULL, 'Luxury Yacht Charter Caribbean | Syrama Yachting', 'Charter a luxury yacht in the Caribbean with Syrama Yachting. From the British Virgin Islands to St Barths and the Bahamas, cruise warm winter waters aboard a curated fleet.', 'Luxury Yacht Charter in the Caribbean', '/images/regions/Caribbean.webp', 'West Indies', ARRAY['The Caribbean is where the charter calendar turns south for winter. While the Mediterranean season winds down after September, the trade winds and warm, reliable weather across the British Virgin Islands, St Barths, the Bahamas and the wider West Indies make December through April the region''s high season — a natural complement to a French Riviera or Balearic summer for anyone chartering more than once a year.', 'Syrama Yachting arranges Caribbean charters across the region''s main hubs, with the crew and itinerary built around the islands you want to see and the time of year you''re travelling.'], ARRAY['miami'], now()),
(20, 'sardinia', NULL, 'Sardinia', 'Sardinia', NULL, 'Luxury Yacht Charter Sardinia | Syrama Yachting', 'Charter a luxury yacht in Sardinia with Syrama Yachting. Cruise the Costa Smeralda, Porto Cervo and the La Maddalena archipelago aboard a curated fleet.', 'Luxury Yacht Charter in Sardinia', '/images/regions/Sardinia.webp', 'Mediterranean', ARRAY['Sardinia''s Costa Smeralda has been a fixture of Mediterranean yachting since the 1960s, and the water still explains why: the shallow bays along the northeast coast run from turquoise to deep emerald, framed by granite headlands and the small, protected islands of the La Maddalena archipelago just offshore. Porto Cervo remains the coast''s best-known harbour, but the island''s appeal runs well beyond it.', 'Syrama Yachting arranges charters around Sardinia, concentrated on the Costa Smeralda and La Maddalena in the northeast, with itineraries that can extend across the Strait of Bonifacio to Corsica for those with more time.'], ARRAY['corsica', 'italy', 'french-riviera'], now()),
(21, 'miami', NULL, 'Miami', 'Miami', NULL, 'Luxury Yacht Charter Miami | Private Yacht Rental | Syrama Yachting', 'Charter a luxury yacht in Miami with Syrama Yachting. Cruise Biscayne Bay, South Beach and Government Cut, or head further out toward the Bahamas, aboard a curated fleet.', 'Luxury Yacht Charter in Miami', '/images/regions/Miami.webp', 'Florida, USA', ARRAY['Miami charters year-round on warm, sheltered water, with Biscayne Bay providing calm conditions for a half-day on the water and Government Cut opening straight onto the Atlantic for anyone continuing toward the Bahamas. The skyline along South Beach and Downtown is as much a part of the experience as the water itself, and the charter scene here runs on short, flexible bookings rather than the week-long itineraries typical of the Mediterranean.', 'Syrama Yachting arranges Miami charters departing mainly from Biscayne Bay and the Miami River, with hourly and daily rates depending on the yacht and the option to extend an itinerary toward the Bahamas for those with more time.'], ARRAY['caribbean'], now());

SELECT setval(pg_get_serial_sequence('"destination"', 'id'), 21, true);

INSERT INTO "destination_faq" ("id", "destination_id", "question", "answer", "position") VALUES
(1, 1, 'What is the best time of year to charter a yacht in Cannes?', 'The charter season on the French Riviera runs roughly from May to September, with July and August the busiest around the Cannes Film Festival period in May and peak summer. Spring and early autumn offer calmer waters and more availability.', 0),
(2, 1, 'Do I need a captain to charter a yacht in Cannes?', 'Most yachts in our Cannes fleet are chartered with a professional skipper or full crew included. Our team will confirm exactly what''s included when you request availability for a specific yacht.', 1),
(3, 1, 'Can I combine Cannes with other Riviera destinations?', 'Yes — Cannes is a natural base for day trips to the Lérins Islands, Antibes or Golfe-Juan, and multi-day itineraries toward Saint-Tropez or Monaco are easy to arrange.', 2),
(4, 2, 'When is the best time to charter a yacht in Saint-Tropez?', 'The season runs from spring through early autumn, with July and August the peak. Late June and September offer a similar experience with fewer crowds in the harbour.', 0),
(5, 2, 'Is Saint-Tropez suitable for a day charter?', 'Yes — many of our Saint-Tropez yachts are available for a half-day or full-day charter, ideal for reaching Pampelonne beach or a swim stop in the Gulf.', 1),
(6, 2, 'Can I charter a yacht in Saint-Tropez for a week?', 'Weekly charters are available on part of our fleet, with itineraries that can extend toward Cannes, Monaco or along the Var coastline depending on the yacht.', 2),
(7, 3, 'What is the best time to charter a yacht in Monaco?', 'The charter season runs from spring to autumn. Late May, around the Monaco Grand Prix, and July–August are the busiest periods, so early booking is recommended.', 0),
(8, 3, 'Can I charter a yacht in Monaco for a single day?', 'Yes — several yachts in our Monaco fleet are available for day charters departing from Port Hercules, ideal for exploring Cap Ferrat or Menton.', 1),
(9, 3, 'Do Monaco yacht charters include a crew?', 'Most yachts available for charter from Monaco come with a skipper or full crew. Exact inclusions are confirmed per yacht when you request availability.', 2),
(10, 4, 'When is the best time to charter a yacht in Juan-les-Pins?', 'The season runs from May to September, with July and August — including the Jazz à Juan festival — the busiest. Late spring and September offer calmer conditions.', 0),
(11, 4, 'Is Juan-les-Pins suitable for a day charter?', 'Yes — the sheltered Golfe-Juan bay makes it an easy, calm departure point for a half-day or full-day charter toward Cap d''Antibes or the Lérins Islands.', 1),
(12, 4, 'Can I charter a yacht in Juan-les-Pins that also visits Cannes?', 'Yes — Cannes is a short cruise east along the coast, and several yachts in our fleet can combine both in one itinerary.', 2),
(13, 5, 'When is the best time to charter a yacht in Beaulieu-sur-Mer?', 'The season runs from May to September, with July and August the busiest. The bay''s sheltered microclimate makes spring and early autumn charters comfortable too.', 0),
(14, 5, 'Is Beaulieu-sur-Mer close to Monaco?', 'Yes — Monaco is one of the shortest crossings from Beaulieu, making it an easy day-charter combination alongside Cap Ferrat.', 1),
(15, 5, 'Do Beaulieu-sur-Mer yacht charters include a crew?', 'Most yachts available for charter from Beaulieu come with a skipper or full crew. Exact inclusions are confirmed per yacht when you request availability.', 2),
(16, 6, 'When is the best time to charter a yacht in Saint-Jean-Cap-Ferrat?', 'The season runs from May to September, with July and August the busiest. Spring and early autumn offer calmer water around the cape.', 0),
(17, 6, 'Can I charter a yacht in Cap Ferrat for a single day?', 'Yes — several yachts in our fleet are available for a half-day or full-day charter, ideal for a circuit of the cape or a run to Monaco.', 1),
(18, 6, 'Does a Cap Ferrat charter include a crew?', 'Most yachts available for charter here come with a skipper or full crew. Exact inclusions are confirmed per yacht when you request availability.', 2),
(19, 7, 'When is the best time to charter a yacht in Menton?', 'The season runs from May to September, with July and August the busiest. Menton''s sheltered microclimate makes spring and early autumn charters comfortable too.', 0),
(20, 7, 'Can a Menton yacht charter cross into Italy?', 'Yes — the Italian border is a short cruise away, and several yachts in our fleet can combine Menton with a run along the Italian Riviera.', 1),
(21, 7, 'Is Menton close to Monaco?', 'Yes — Monaco is one of the shortest crossings from Menton, making it an easy addition to a Menton-based itinerary.', 2),
(22, 8, 'When is the best time to charter a yacht in Golfe-Juan?', 'The season runs from May to September, with July and August the busiest. Late spring and September offer calmer, quieter conditions.', 0),
(23, 8, 'Is Golfe-Juan close to Cannes?', 'Yes — Cannes is a short cruise west along the bay, making it an easy addition to a Golfe-Juan-based itinerary.', 1),
(24, 8, 'Do Golfe-Juan yacht charters include a crew?', 'Most yachts available for charter here come with a skipper or full crew. Exact inclusions are confirmed per yacht when you request availability.', 2),
(25, 9, 'When is the best time to charter a yacht in Saint-Raphaël?', 'The season runs from May to September, with July and August the busiest. Late spring and September offer calmer water along the Estérel coast.', 0),
(26, 9, 'Is Saint-Raphaël a good base for reaching Saint-Tropez?', 'Yes — the Gulf of Saint-Tropez is a direct crossing east, making Saint-Raphaël a quieter alternative departure point for the same itinerary.', 1),
(27, 9, 'Do Saint-Raphaël yacht charters include a crew?', 'Most yachts available for charter here come with a skipper or full crew. Exact inclusions are confirmed per yacht when you request availability.', 2),
(28, 10, 'When is the best time to charter a yacht in Nice?', 'The season runs from May to September, with July and August the busiest. Nice''s position makes it workable for shoulder-season charters too.', 0),
(29, 10, 'How many yachts are available for charter from Nice?', 'Our Nice-based fleet is currently small. If nothing available matches what you''re after, our team can suggest a yacht departing from nearby Beaulieu, Cap Ferrat or Antibes instead.', 1),
(30, 10, 'Is Nice a good base for exploring the wider Riviera?', 'Yes — its central position and international airport make it a practical starting point for an itinerary that ranges from Cap Ferrat and Monaco to Antibes and Cannes.', 2),
(31, 11, 'When is the best time to charter a yacht in Antibes?', 'The season runs from May to September, with July and August the busiest around Port Vauban and Cap d''Antibes.', 0),
(32, 11, 'How many yachts are available for charter from Antibes?', 'Our Antibes-based fleet is currently small. If nothing available matches what you''re after, our team can suggest a yacht departing from nearby Cannes, Juan-les-Pins or Golfe-Juan instead.', 1),
(33, 11, 'Is Antibes close to Cannes and the Lérins Islands?', 'Yes — both are a short cruise away, making Antibes a practical base for the same stretch of coast.', 2),
(34, 12, 'How are Dubai yacht charters priced?', 'Most yachts in our Dubai fleet are chartered by the hour, with some available on a daily rate — pricing depends on the yacht. Some yachts also have a minimum charter duration, shown on request.', 0),
(35, 12, 'What is the best time to charter a yacht in Dubai?', 'Dubai can be chartered year-round. The cooler months from October to April are the most popular, though summer charters are available with calmer, warmer waters.', 1),
(36, 12, 'Where do Dubai yacht charters depart from?', 'Departure points vary by yacht, with Dubai Marina the most common. Exact details are confirmed when you request availability for a specific yacht.', 2),
(37, 13, 'When is the best time to charter a yacht on the French Riviera?', 'The season runs from May to September, with July and August the busiest. May, June and September offer similar conditions with more availability.', 0),
(38, 13, 'Which French Riviera destinations does Syrama Yachting cover?', 'Our fleet is concentrated around Cannes, Saint-Tropez and Monaco, with yachts also based in Nice, Antibes, Menton and other Riviera ports.', 1),
(39, 13, 'Can I charter a yacht for a multi-day trip along the Riviera?', 'Yes — several yachts in our fleet are available for multi-day or weekly charters, with itineraries spanning multiple Riviera destinations.', 2),
(40, 14, 'When is the best time to charter a yacht in the Balearic Islands?', 'The season runs from May to October, with July and August the busiest around Ibiza. June and September offer warm water and quieter anchorages.', 0),
(41, 14, 'Can I charter a yacht that moves between Ibiza, Formentera and Mallorca?', 'Yes — multi-island itineraries are one of the main reasons to charter in the Balearics, and several yachts in our fleet are set up for exactly that.', 1),
(42, 14, 'Do I need charter experience to book a yacht in the Balearics?', 'No — most yachts come with a professional skipper or full crew. Exact inclusions are confirmed per yacht when you request availability.', 2),
(43, 15, 'When is the best time to charter a yacht in Greece?', 'The season runs from May to October. July and August bring the strongest meltemi winds in the Cyclades; late spring and September offer calmer sailing with fewer crowds.', 0),
(44, 15, 'Which part of Greece is best for a first yacht charter?', 'The Ionian Islands are generally calmer and better suited to a first charter, while the Cyclades reward more experienced sailing in peak summer. Our team can match the itinerary to your experience.', 1),
(45, 15, 'Can I charter a yacht in Greece for island-hopping?', 'Yes — island-hopping is the standard way to charter in Greece, and our fleet is arranged with multi-island itineraries in mind.', 2),
(46, 16, 'When is the best time to charter a yacht in Italy?', 'The season runs from May to September, with July and August the busiest around Capri and the Amalfi Coast. May, June and September offer similar weather with more availability.', 0),
(47, 16, 'Is the Amalfi Coast suitable for a day charter?', 'Yes — many of our Italy yachts are available for a half-day or full-day charter, ideal for Capri or a stretch of the Amalfi Coast.', 1),
(48, 16, 'Can I combine the Amalfi Coast with Sicily or the Aeolian Islands?', 'Longer itineraries connecting the Amalfi Coast to Sicily and the Aeolian Islands are possible on part of our fleet — our team can confirm what suits your dates.', 2),
(49, 17, 'When is the best time to charter a yacht in Corsica?', 'The season runs from May to September, with July and August the busiest around Bonifacio and Porto-Vecchio. Late spring and September offer calmer anchorages.', 0),
(50, 17, 'Can I charter a yacht in Corsica that also visits Sardinia?', 'Yes — the Strait of Bonifacio between Corsica and Sardinia is a short crossing, and several yachts in our fleet can arrange an itinerary spanning both islands.', 1),
(51, 17, 'Is Corsica reachable from the French Riviera by yacht?', 'Yes, though it''s a longer open-water crossing rather than a day trip. Some multi-day charters combine the Riviera with Corsica — our team can advise on timing.', 2),
(52, 18, 'When is the best time to charter a yacht in the Maldives?', 'The dry season from November to April, with calmer seas and less rain, is the classic charter window. The south-west monsoon from May to October brings more rain and swell.', 0),
(53, 18, 'How is a Maldives yacht charter different from the Mediterranean?', 'Itineraries move between atolls and islands rather than along a coastline, and the season runs opposite to the Mediterranean — making it a natural winter charter when Riviera season has ended.', 1),
(54, 18, 'Do Maldives yacht charters include a crew?', 'Yes — charters in the Maldives are crewed, given the navigation between atolls. Exact inclusions are confirmed per yacht when you request availability.', 2),
(55, 19, 'When is the best time to charter a yacht in the Caribbean?', 'The high season runs from December to April, in the dry season and outside the June–November hurricane window. This also makes it a natural counter-season to a Mediterranean summer charter.', 0),
(56, 19, 'Which Caribbean islands does Syrama Yachting cover?', 'Our Caribbean fleet covers the British Virgin Islands, St Barths and St Martin, and the Bahamas, among other West Indies destinations — confirmed per yacht when you request availability.', 1),
(57, 19, 'Is the Caribbean suitable for a first-time charter guest?', 'Yes — most itineraries involve short, sheltered hops between islands, and yachts come with a professional crew handling navigation and logistics.', 2),
(58, 20, 'When is the best time to charter a yacht in Sardinia?', 'The season runs from May to September, with July and August the busiest around the Costa Smeralda. Late spring and September offer calmer conditions with more availability.', 0),
(59, 20, 'Can I charter a yacht in Sardinia that also visits Corsica?', 'Yes — the Strait of Bonifacio is a short crossing, and several yachts in our fleet can arrange an itinerary spanning both Sardinia and Corsica.', 1),
(60, 20, 'Is the Costa Smeralda suitable for a day charter?', 'Yes — several yachts in our Sardinia fleet are available for a half-day or full-day charter around Porto Cervo and the nearby bays.', 2),
(61, 21, 'How are Miami yacht charters priced?', 'Most yachts in our Miami fleet are chartered by the hour, with some available on a daily rate — pricing depends on the yacht, and some have a minimum charter duration.', 0),
(62, 21, 'What is the best time to charter a yacht in Miami?', 'Miami can be chartered year-round. Winter and spring (November to May) are the most popular and fall outside the June–November hurricane season.', 1),
(63, 21, 'Can a Miami yacht charter cross to the Bahamas?', 'Yes, on part of our fleet — a Bahamas crossing needs a longer charter and suitable weather, which our team can confirm when you request availability.', 2);

SELECT setval(pg_get_serial_sequence('"destination_faq"', 'id'), 63, true);

INSERT INTO "destination_itinerary" ("id", "destination_id", "name", "description", "position") VALUES
(1, 1, 'Îles de Lérins', 'A short crossing from Cannes to Île Sainte-Marguerite and Île Saint-Honorat — pine forests, clear anchorages and a fortress once used as a royal prison.', 0),
(2, 1, 'Antibes & Juan-les-Pins', 'West along the coast to the old town of Antibes and the beaches of Juan-les-Pins, past Cap d''Antibes.', 1),
(3, 1, 'Saint-Tropez', 'A classic full-day Riviera crossing to the Gulf of Saint-Tropez, past Sainte-Maxime and the Pampelonne coastline.', 2),
(4, 2, 'Pampelonne Beach', 'A short run from the port to Pampelonne, Saint-Tropez''s famous stretch of beach and beach clubs, ideal for an anchored lunch.', 0),
(5, 2, 'Gulf of Saint-Tropez', 'A relaxed cruise across the bay to Sainte-Maxime and Port Grimaud, with calm waters well suited to swimming stops.', 1),
(6, 2, 'Cannes', 'A full-day crossing east along the coast to Cannes and the Lérins Islands.', 2),
(7, 3, 'Cap Ferrat & Beaulieu-sur-Mer', 'A short cruise west to the villas and coves of Saint-Jean-Cap-Ferrat and Beaulieu-sur-Mer.', 0),
(8, 3, 'Menton & the Italian border', 'East along the coast past Roquebrune-Cap-Martin to Menton, with the Italian Riviera visible beyond.', 1),
(9, 3, 'Cannes & Saint-Tropez', 'For longer charters, a westward itinerary toward Cannes and, further still, the Gulf of Saint-Tropez.', 2),
(10, 4, 'Cap d''Antibes', 'A short cruise around the wooded Cap d''Antibes peninsula, past its villas and the Sentier du Littoral coastal path.', 0),
(11, 4, 'Îles de Lérins', 'A crossing to Île Sainte-Marguerite and Île Saint-Honorat, the pine-covered islands just off Cannes.', 1),
(12, 4, 'Golfe-Juan to Cannes', 'A short run along the bay to Cannes and the Croisette.', 2),
(13, 5, 'Saint-Jean-Cap-Ferrat', 'A short cruise around the neighbouring Cap Ferrat peninsula, past its villas and the Villa Ephrussi de Rothschild.', 0),
(14, 5, 'Monaco & Monte-Carlo', 'East along the coast to Port Hercules and Monte-Carlo, one of the shortest crossings on this stretch of coast.', 1),
(15, 5, 'Nice & the Baie des Anges', 'West to Nice and the Promenade des Anglais, curving around the Baie des Anges.', 2),
(16, 6, 'Around the Cape', 'A full circuit of the peninsula, past the Villa Ephrussi de Rothschild gardens and the villas on both shores.', 0),
(17, 6, 'Beaulieu-sur-Mer & Monaco', 'A short cruise to neighbouring Beaulieu, then on to Port Hercules and Monte-Carlo.', 1),
(18, 6, 'Nice & the Baie des Anges', 'West around the Baie des Anges to Nice and the Promenade des Anglais.', 2),
(19, 7, 'The Italian Riviera', 'A short crossing over the border to Ventimiglia and Bordighera on the Italian coast.', 0),
(20, 7, 'Monaco & Roquebrune-Cap-Martin', 'West along the coast past Roquebrune-Cap-Martin to Port Hercules and Monte-Carlo.', 1),
(21, 7, 'Cap Ferrat & Beaulieu', 'For longer charters, a westward run toward Cap Ferrat and Beaulieu-sur-Mer.', 2),
(22, 8, 'Îles de Lérins', 'A short crossing to Île Sainte-Marguerite and Île Saint-Honorat, roughly equidistant from Golfe-Juan as from Cannes.', 0),
(23, 8, 'Cap d''Antibes', 'East along the bay to Juan-les-Pins and around the wooded Cap d''Antibes peninsula.', 1),
(24, 8, 'Cannes & the Croisette', 'A short run west to Cannes and the Croisette.', 2),
(25, 9, 'The Estérel Coastline', 'A scenic cruise beneath the red cliffs and calanques of the Massif de l''Estérel toward Théoule-sur-Mer.', 0),
(26, 9, 'The Gulf of Saint-Tropez', 'East across the bay to Sainte-Maxime, Pampelonne beach and Saint-Tropez itself.', 1),
(27, 9, 'Cannes & the Lérins Islands', 'West along the coast toward Cannes and the pine-covered Lérins Islands.', 2),
(28, 10, 'Cap Ferrat & Beaulieu-sur-Mer', 'East around the Baie des Anges to the villas of Cap Ferrat and the sheltered bay at Beaulieu.', 0),
(29, 10, 'Monaco & Monte-Carlo', 'Further east to Port Hercules and Monte-Carlo, a natural extension of a Cap Ferrat run.', 1),
(30, 10, 'Antibes & Cap d''Antibes', 'West along the coast to Antibes and its wooded cape.', 2),
(31, 11, 'Cap d''Antibes', 'A circuit of the wooded peninsula south of town, past its villas and the Sentier du Littoral coastal path.', 0),
(32, 11, 'Îles de Lérins', 'A short crossing to Île Sainte-Marguerite and Île Saint-Honorat, off the coast at Cannes.', 1),
(33, 11, 'Juan-les-Pins & Golfe-Juan', 'Around the cape to Juan-les-Pins and the sheltered Golfe-Juan bay.', 2),
(34, 12, 'Dubai Marina & JBR', 'A short cruise along the Marina skyline and Jumeirah Beach Residence, ideal for a sunset run.', 0),
(35, 12, 'Palm Jumeirah', 'Circle the Palm Jumeirah for views of its waterfront villas and the Atlantis resort at its crest.', 1),
(36, 12, 'Burj Al Arab', 'Cruise past the Burj Al Arab and Jumeirah Beach for one of Dubai''s most photographed views from the water.', 2),
(37, 13, 'Cannes to the Lérins Islands', 'A short crossing from Cannes to Île Sainte-Marguerite and Île Saint-Honorat.', 0),
(38, 13, 'The Gulf of Saint-Tropez', 'Pampelonne beach, Sainte-Maxime and the anchorages around the Gulf.', 1),
(39, 13, 'Monaco to Cap Ferrat', 'Port Hercules to the villas of Saint-Jean-Cap-Ferrat and on to Menton.', 2),
(40, 14, 'Ibiza to Formentera', 'A short crossing south to Formentera''s Ses Illetes and Es Caló, among the clearest anchorages in the Mediterranean.', 0),
(41, 14, 'Dalt Vila & the North of Ibiza', 'From the UNESCO-listed old town of Ibiza to the quieter calas of Portinatx and Cala Xarraca in the north.', 1),
(42, 14, 'Mallorca''s Tramuntana Coast', 'The dramatic western coastline of Mallorca, from Palma toward Sóller and the cliffs of the Tramuntana range.', 2),
(43, 15, 'The Cyclades', 'Mykonos, Paros and Santorini — the classic Aegean circuit, best sailed outside the peak-August meltemi if a calmer crossing matters.', 0),
(44, 15, 'The Ionian Islands', 'Corfu, Paxos and Kefalonia on Greece''s more sheltered western coast, with turquoise coves and shorter hops between anchorages.', 1),
(45, 15, 'The Saronic Gulf', 'A short run from Athens to Hydra, Spetses and the Peloponnese coast, ideal for a shorter charter close to the mainland.', 2),
(46, 16, 'The Amalfi Coast & Capri', 'Positano, Amalfi and the Faraglioni rocks off Capri — the definitive southern Italy itinerary.', 0),
(47, 16, 'Portofino & the Ligurian Coast', 'The harbour of Portofino and the villages of the Cinque Terre along Italy''s northwestern coastline.', 1),
(48, 16, 'The Aeolian Islands', 'Off Sicily''s north coast, Lipari, Panarea and Stromboli — quieter, volcanic islands with fewer crowds.', 2),
(49, 17, 'Bonifacio & the Lavezzi Islands', 'The clifftop citadel of Bonifacio and a short crossing to the protected Îles Lavezzi nature reserve.', 0),
(50, 17, 'Porto-Vecchio & the Southeast Coast', 'Palombaggia and Santa Giulia beaches, among the most photographed stretches of coastline on the island.', 1),
(51, 17, 'Scandola Nature Reserve', 'A UNESCO World Heritage site on the west coast, its red volcanic cliffs and calanques accessible only from the water.', 2),
(52, 18, 'North Malé Atoll', 'The atoll closest to the capital and main airport, with sandbanks, reef breaks and easy access for shorter charters.', 0),
(53, 18, 'Baa Atoll', 'A UNESCO Biosphere Reserve known for its reefs and, seasonally, manta ray and whale shark aggregations at Hanifaru Bay.', 1),
(54, 18, 'Ari Atoll', 'Further from Malé and quieter, with some of the archipelago''s best-known dive and snorkel sites.', 2),
(55, 19, 'The British Virgin Islands', 'Tortola, Virgin Gorda and the Baths — short hops between islands with some of the most sheltered sailing in the Caribbean.', 0),
(56, 19, 'St Barths & St Martin', 'Gustavia''s harbour and the beaches of St Barths, a short crossing from St Martin.', 1),
(57, 19, 'The Exumas, Bahamas', 'A chain of over 300 cays north of the Caribbean proper, known for shallow, brilliantly clear water and swimming pigs at Big Major Cay.', 2),
(58, 20, 'Costa Smeralda & Porto Cervo', 'The Emerald Coast''s bays and coves around Porto Cervo, the region''s best-known yachting harbour.', 0),
(59, 20, 'La Maddalena Archipelago', 'A national park of seven main islands and dozens of granite islets, with some of Sardinia''s clearest anchorages.', 1),
(60, 20, 'The Strait of Bonifacio to Corsica', 'A short crossing north to Corsica for itineraries with time to cover both islands.', 2),
(61, 21, 'Biscayne Bay & South Beach', 'A sheltered cruise past the South Beach skyline and the private islands of Biscayne Bay, ideal for a half-day charter.', 0),
(62, 21, 'Government Cut & Fisher Island', 'Out through Government Cut past Fisher Island, with open Atlantic water beyond the port.', 1),
(63, 21, 'Bimini & the Bahamas', 'For longer charters, a crossing to Bimini and the western Bahamas, roughly 50 nautical miles from Miami.', 2);

SELECT setval(pg_get_serial_sequence('"destination_itinerary"', 'id'), 63, true);
