import { prisma } from '@/lib/prisma'
import { cookies } from 'next/headers'
import { randomBytes } from 'crypto'
import { findConflictingReservations, combineDateTime } from '@/lib/booking-availability'

async function checkAuth() {
  const cookieStore = await cookies()
  const userId = cookieStore.get('userId')?.value
  if (!userId) {
    throw new Error('Unauthorized')
  }
}

function generateToken() {
  return randomBytes(8).toString('base64url')
}

// GET — booking links, optionally scoped to one yacht (the "Generate
// Booking Link" modal's own history) or across the whole fleet (the admin
// Booking Links page), optionally filtered by status and paginated.
export async function GET(request: Request) {
  try {
    await checkAuth()
    const { searchParams } = new URL(request.url)
    const yachtId = searchParams.get('yachtId')
    const status = searchParams.get('status')
    const page = parseInt(searchParams.get('page') || '1')
    const limit = parseInt(searchParams.get('limit') || '20')
    const skip = (page - 1) * limit

    // Yacht scoping applies to the stat cards too (so they read "for this
    // yacht" when filtered), but the status filter only narrows the list
    // itself — otherwise picking "Booked" would make the Pending stat
    // card read 0, which looks like a bug rather than a filter.
    const baseWhere: { yachtId?: number } = {}
    if (yachtId) baseWhere.yachtId = parseInt(yachtId)

    const where: { yachtId?: number; status?: string } = { ...baseWhere }
    if (status) where.status = status

    const [links, total, totalPending, totalCompleted] = await Promise.all([
      prisma.bookingLink.findMany({
        where,
        include: {
          yacht: { select: { id: true, model: true, builder: true, media: { select: { url: true }, take: 1 } } },
        },
        orderBy: { createdAt: 'desc' },
        skip,
        take: limit,
      }),
      prisma.bookingLink.count({ where: baseWhere }),
      prisma.bookingLink.count({ where: { ...baseWhere, status: 'pending' } }),
      prisma.bookingLink.count({ where: { ...baseWhere, status: 'completed' } }),
    ])

    // BookingLink.reservationId is a loose reference (no formal relation),
    // so the client's name and contract are fetched separately for
    // completed links.
    const reservationIds = links.map((l) => l.reservationId).filter((id): id is number => id != null)
    const reservations = reservationIds.length > 0
      ? await prisma.reservation.findMany({
          where: { id: { in: reservationIds } },
          select: { id: true, client: { select: { fullName: true } }, contract: { select: { id: true } } },
        })
      : []
    const reservationById = new Map(reservations.map((r) => [r.id, r]))

    const linksWithClient = links.map((l) => {
      const reservation = l.reservationId ? reservationById.get(l.reservationId) : undefined
      return {
        ...l,
        clientName: reservation?.client.fullName || null,
        contractId: reservation?.contract?.id || null,
      }
    })

    return Response.json({
      links: linksWithClient,
      currentPage: page,
      totalPages: Math.ceil(total / limit),
      total,
      totalPending,
      totalCompleted,
    })
  } catch (error) {
    console.error('List booking links error:', error)
    return Response.json({ error: 'Failed to fetch booking links' }, { status: 500 })
  }
}

// DELETE — withdraw a pending link (e.g. generated by mistake, or
// superseded by a new one). A completed link can't be deleted since it's
// tied to a real reservation.
export async function DELETE(request: Request) {
  try {
    await checkAuth()
    const { searchParams } = new URL(request.url)
    const id = searchParams.get('id')

    if (!id) {
      return Response.json({ error: 'id is required' }, { status: 400 })
    }

    const link = await prisma.bookingLink.findUnique({ where: { id: parseInt(id) } })
    if (!link) {
      return Response.json({ error: 'Booking link not found' }, { status: 404 })
    }
    if (link.status === 'completed') {
      return Response.json({ error: 'Cannot delete a completed booking link' }, { status: 400 })
    }

    await prisma.bookingLink.delete({ where: { id: parseInt(id) } })

    return Response.json({ success: true })
  } catch (error) {
    console.error('Delete booking link error:', error)
    return Response.json({ error: 'Failed to delete booking link' }, { status: 500 })
  }
}

// POST create a booking link for one yacht + date/time slot — the admin
// shares the resulting URL (e.g. over WhatsApp) instead of relaying the
// client's contact details back and forth manually.
//
// Can also be generated "from" an existing reservation that has no
// contract yet (e.g. a legacy import, or one added manually from the
// Clients/Reservations page) — pass `reservationId` instead of `yachtId`.
// The link is then tied to that reservation, and submitting it will
// attach the contract to it instead of creating a brand-new reservation.
export async function POST(request: Request) {
  try {
    await checkAuth()
    const data = await request.json()
    const { yachtId, reservationId, date, endDate, startTime, endTime } = data

    let resolvedYachtId: number
    let sourceReservationId: number | null = null

    if (reservationId) {
      const reservation = await prisma.reservation.findUnique({
        where: { id: parseInt(reservationId) },
        select: { id: true, yachtId: true, contract: { select: { id: true } } },
      })
      if (!reservation) {
        return Response.json({ error: 'Reservation not found' }, { status: 404 })
      }
      if (!reservation.yachtId) {
        return Response.json({ error: 'This reservation has no yacht attached' }, { status: 400 })
      }
      if (reservation.contract) {
        return Response.json({ error: 'This reservation already has a contract' }, { status: 400 })
      }
      resolvedYachtId = reservation.yachtId
      sourceReservationId = reservation.id
    } else {
      if (!yachtId) {
        return Response.json({ error: 'Yacht, date and start time are required' }, { status: 400 })
      }
      const yacht = await prisma.yacht.findUnique({ where: { id: parseInt(yachtId) }, select: { id: true } })
      if (!yacht) {
        return Response.json({ error: 'Yacht not found' }, { status: 404 })
      }
      resolvedYachtId = yacht.id
    }

    if (!date || !startTime) {
      return Response.json({ error: 'Yacht, date and start time are required' }, { status: 400 })
    }

    // Vanishingly unlikely to collide, but retry a couple of times rather
    // than fail outright if it ever does.
    let link
    for (let attempt = 0; attempt < 3; attempt++) {
      try {
        link = await prisma.bookingLink.create({
          data: {
            token: generateToken(),
            yachtId: resolvedYachtId,
            date: new Date(date),
            endDate: endDate ? new Date(endDate) : null,
            startTime,
            endTime: endTime || null,
            reservationId: sourceReservationId,
          },
        })
        break
      } catch (err) {
        const isDuplicateToken = err instanceof Error && 'code' in err && (err as { code?: string }).code === 'P2002'
        if (isDuplicateToken && attempt < 2) continue
        throw err
      }
    }

    // Soft warning only — the admin may still want to send this link out
    // (e.g. as a backup in case the existing booking falls through), the
    // hard block only happens when a link is actually completed.
    const rangeStart = new Date(date)
    const rangeEndDay = endDate ? new Date(endDate) : rangeStart
    const conflicts = await findConflictingReservations(resolvedYachtId, {
      start: combineDateTime(rangeStart, startTime),
      end: endTime ? combineDateTime(rangeEndDay, endTime) : rangeEndDay,
    }, sourceReservationId || undefined)

    return Response.json({
      token: link!.token,
      conflicts: conflicts.map((c) => ({ date: c.date, endDate: c.endDate, client: c.client.fullName })),
    }, { status: 201 })
  } catch (error) {
    console.error('Create booking link error:', error)
    return Response.json({ error: 'Failed to create booking link' }, { status: 500 })
  }
}
